/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:08:08 GMT 2024
 */

package dk.tbsalling.aismessages.ais;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.tbsalling.aismessages.ais.Decoders;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Decoders_ESTest extends Decoders_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Decoders decoders0 = new Decoders();
  }
}
