package org.apache.commons.graph.export;

import java.io.File;
import java.io.OutputStream;
import java.io.Writer;
import java.util.Map;
import org.apache.commons.graph.ContextInitializer;
import org.apache.commons.graph.ExceptionHandler;
import org.apache.commons.graph.Graph;
import org.apache.commons.graph.Mapper;
import org.graalvm.polyglot.PolyglotException;
import org.graalvm.polyglot.Value;

abstract class AbstractExporter<V, E, T extends AbstractExporter<V, E, T>> {
  private static final String G = "G";
  private static Value clz =
      ContextInitializer.getPythonClass("/export/AbstractExporter.py", "AbstractExporter");
  private Value obj;

  public AbstractExporter(Value obj) {
    this.obj = obj;
  }

  public Value getPythonObject() {
    return obj;
  }

  public final void to2(Writer writer) throws GraphExportException {
    try {
      //
      // this.writer = checkNotNull(writer, "Impossibe to export the graph in a null stream");
      //
      // try {
      // startSerialization();
      // comment(format("Graph generated by Apache Commons Graph on %s%n", new Date()));
      //
      // startGraph(name);
      //
      // for (V vertex : graph.getVertices0()) {
      // Map<String, Object> properties =
      // new HashMap<String, Object>(vertexProperties.size());
      //
      // for (Entry<String, Mapper<V, ?>> vertexProperty : vertexProperties.entrySet()) {
      // properties.put(vertexProperty.getKey(), vertexProperty.getValue().map(vertex));
      // }
      //
      // vertex(vertex, properties);
      // }
      //
      // for (E edge : graph.getEdges()) {
      // VertexPair<V> vertices = graph.getVertices1(edge);
      //
      // Map<String, Object> properties = new HashMap<String, Object>(edgeProperties.size());
      //
      // for (Entry<String, Mapper<E, ?>> edgeProperty : edgeProperties.entrySet()) {
      // properties.put(edgeProperty.getKey(), edgeProperty.getValue().map(edge));
      // }
      //
      // edge(edge, vertices.getHead(), vertices.getTail(), properties);
      // }
      //
      // endGraph();
      //
      // endSerialization();
      // } catch (Exception e) {
      // throw new GraphExportException(
      // e,
      // "an error occurred while exporting graph %s (named %s) to writer %s",
      // graph,
      // name,
      // writer);
      // } finally {
      // try {
      // writer.close();
      // } catch (IOException e) {
      // }
      // }
      //

      obj.invokeMember("to2", writer);
    } catch (PolyglotException e) {
      // TODO: Handle GraphExportException
      throw (GraphExportException) ExceptionHandler.handle(e, "AbstractExporter.to2");
    }
  }

  public final void to1(OutputStream outputStream) throws GraphExportException {
    try {
      //
      // to2(
      // new OutputStreamWriter(
      // checkNotNull(
      // outputStream, "Impossibe to export the graph in a null stream")));
      //

      obj.invokeMember("to1", outputStream);
    } catch (PolyglotException e) {
      // TODO: Handle GraphExportException
      throw (GraphExportException) ExceptionHandler.handle(e, "AbstractExporter.to1");
    }
  }

  public final void to0(File outputFile) throws GraphExportException {
    try {
      //
      // try {
      // to1(
      // new FileOutputStream(
      // checkNotNull(
      // outputFile, "Impossibe to export the graph in a null file")));
      // } catch (FileNotFoundException e) {
      // throw new RuntimeException(e);
      // }
      //

      obj.invokeMember("to0", outputFile);
    } catch (PolyglotException e) {
      // TODO: Handle GraphExportException
      throw (GraphExportException) ExceptionHandler.handle(e, "AbstractExporter.to0");
    }
  }

  protected final Writer getWriter() {
    //
    // return writer;
    //

    // TODO: Check the type mapping below!
    return obj.invokeMember("getWriter").as(Writer.class);
  }

  protected final Graph<V, E> getGraph() {
    //
    // return graph;
    //

    // TODO: Check the type mapping below!
    return obj.invokeMember("getGraph").as(Graph.class);
  }

  protected void addVertexProperty(String propertyName, Mapper<V, ?> vertexProperty) {
    //
    // this.vertexProperties.put(propertyName, vertexProperty);
    //

    obj.invokeMember("addVertexProperty", propertyName, vertexProperty);
  }

  protected void addEdgeProperty(String propertyName, Mapper<E, ?> edgeProperty) {
    //
    // this.edgeProperties.put(propertyName, edgeProperty);
    //

    obj.invokeMember("addEdgeProperty", propertyName, edgeProperty);
  }

  public AbstractExporter(Graph<V, E> graph, String name) {
    //
    // this.graph = graph;
    // this.writer = null;
    // this.vertexProperties = new HashMap<String, Mapper<V, ?>>();
    // this.edgeProperties = new HashMap<String, Mapper<E, ?>>();
    // this.name = name != null ? name : G;
    //

    this.obj = clz.invokeMember("__init__", graph, name);
  }

  protected abstract void vertex(V vertex, Map<String, Object> properties) throws Exception;

  protected abstract void startSerialization() throws Exception;

  protected abstract void startGraph(String name) throws Exception;

  protected abstract void enlistVerticesProperty(String name, Class<?> type) throws Exception;

  protected abstract void enlistEdgesProperty(String name, Class<?> type) throws Exception;

  protected abstract void endSerialization() throws Exception;

  protected abstract void endGraph() throws Exception;

  protected abstract void edge(E edge, V head, V tail, Map<String, Object> properties);

  protected abstract void comment(String text) throws Exception;
}
