name: alphatrans
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openai=1.53.0
  - ollama-python=0.4.4
  - tqdm=4.66.1
  - python-dotenv=1.0.0
  - accelerate=0.24.1
  - black=24.4.2
  - transformers=4.34.1
  - tree_sitter=0.20.3
  - beautifulsoup4=4.12.3
  - pytest-cov=5.0.0
  - tiktoken=0.7.0
