from __future__ import annotations
import time
import re
import os
import datetime
from abc import ABC
import pathlib
from io import StringIO
import io
from io import BytesIO
import typing
from typing import *
from src.main.org.apache.commons.graph.Graph import *
from src.main.org.apache.commons.graph.Mapper import *
from src.main.org.apache.commons.graph.VertexPair import *
from src.main.org.apache.commons.graph.export.GraphExportException import *
from src.main.org.apache.commons.graph.utils.Assertions import *


class AbstractExporter(ABC):

    __writer: typing.Union[io.TextIOWrapper, io.BufferedWriter] = None

    __name: str = ""

    __edgeProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None

    __vertexProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None

    __graph: Graph[typing.Any, typing.Any] = None

    __G: str = "G"

    def to2(self, writer: typing.Union[io.TextIOWrapper, io.BufferedWriter]) -> None:

        self.__writer = writer
        try:
            self._startSerialization()
            self._comment(
                f"Graph generated by Apache Commons Graph on {datetime.now()}"
            )

            self._startGraph(self.__name)

            for vertex in self.__graph.getVertices0():
                properties = {
                    key: value.map(vertex)
                    for key, value in self.__vertexProperties.items()
                }
                self._vertex(vertex, properties)

            for edge in self.__graph.getEdges():
                vertices = self.__graph.getVertices1(edge)
                properties = {
                    key: value.map(edge) for key, value in self.__edgeProperties.items()
                }
                self._edge(edge, vertices.getHead(), vertices.getTail(), properties)

            self._endGraph()

            self._endSerialization()
        except Exception as e:
            raise GraphExportException(
                e,
                "an error occurred while exporting graph %s (named %s) to writer %s",
                self.__graph,
                self.__name,
                self.__writer,
            )
        finally:
            try:
                self.__writer.close()
            except Exception:
                pass

    def to1(
        self, outputStream: typing.Union[io.BytesIO, io.StringIO, io.BufferedWriter]
    ) -> None:

        try:
            self.to2(
                io.TextIOWrapper(
                    Assertions.checkNotNull(
                        outputStream,
                        "Impossibe to export the graph in a null stream",
                        [],
                    )
                )
            )
        except Exception as e:
            raise GraphExportException(
                e,
                "an error occurred while exporting graph %s (named %s) to writer %s",
                self.__graph,
                self.__name,
                self.__writer,
            )

    def to0(self, outputFile: pathlib.Path) -> None:

        try:
            self.to1(
                open(
                    Assertions.checkNotNull(
                        outputFile, "Impossible to export the graph in a null file", []
                    ),
                    "w",
                )
            )
        except Exception as e:
            raise RuntimeError(e)

    def _getWriter(self) -> typing.Union[io.TextIOWrapper, io.BufferedWriter]:
        return self.__writer

    def _getGraph(self) -> Graph[typing.Any, typing.Any]:
        return self.__graph

    def _addVertexProperty(
        self, propertyName: str, vertexProperty: typing.Dict[typing.Any, typing.Any]
    ) -> None:
        self.__vertexProperties[propertyName] = vertexProperty

    def _addEdgeProperty(
        self, propertyName: str, edgeProperty: typing.Dict[typing.Any, typing.Any]
    ) -> None:
        self.__edgeProperties[propertyName] = edgeProperty

    def __init__(self, graph: Graph[typing.Any, typing.Any], name: str) -> None:

        self.__graph = graph
        self.__writer = None
        self.__vertexProperties = {}
        self.__edgeProperties = {}
        self.__name = name if name is not None else self.__G

    def _vertex(
        self, vertex: typing.Any, properties: typing.Dict[str, typing.Any]
    ) -> None:
        pass

    def _startSerialization(self) -> None:

        raise NotImplementedError("Subclass must implement abstract method")

    def _startGraph(self, name: str) -> None:

        self.__writer = io.StringIO()
        self.__name = name
        self.__edgeProperties = {}
        self.__vertexProperties = {}
        self.__graph = Graph()
        self.__G = "G"

    def _enlistVerticesProperty(self, name: str, type: typing.Type[typing.Any]) -> None:
        raise NotImplementedError("Subclass must implement abstract method")

    def _enlistEdgesProperty(self, name: str, type: typing.Type[typing.Any]) -> None:
        raise NotImplementedError("Subclass must implement abstract method")

    def _endSerialization(self) -> None:

        # The abstract method 'endSerialization' is not implemented in the Python version.
        # You need to implement this method in the subclass of AbstractExporter.
        pass

    def _endGraph(self) -> None:

        pass

    def _edge(
        self,
        edge: typing.Any,
        head: typing.Any,
        tail: typing.Any,
        properties: typing.Dict[str, typing.Any],
    ) -> None:

        pass

    def _comment(self, text: str) -> None:
        raise NotImplementedError("Subclass must implement abstract method")
