/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:45:58 GMT 2024
 */

package me.lemire.integercompression.differential;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.differential.IntegratedBinaryPacking;
import me.lemire.integercompression.differential.IntegratedComposition;
import me.lemire.integercompression.differential.IntegratedIntegerCODEC;
import me.lemire.integercompression.differential.IntegratedVariableByte;
import me.lemire.integercompression.differential.XorBinaryPacking;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntegratedComposition_ESTest extends IntegratedComposition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, integratedBinaryPacking0);
      String string0 = integratedComposition0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(integratedBinaryPacking0, integratedVariableByte0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedComposition0.uncompress(intArray0, intWrapper0, (-1), intArray0, intWrapper0);
      assertEquals("-1", intWrapper0.toString());
      assertEquals((-1.0), intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[3];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper((-11));
      integratedComposition0.uncompress(intArray0, intWrapper0, (-1024), intArray0, intWrapper1);
      assertEquals("2", intWrapper0.toString());
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[6];
      intArray1[4] = (-4057);
      integratedComposition0.uncompress(intArray0, intWrapper0, (-4057), intArray1, intWrapper0);
      integratedComposition0.compress(intArray0, intWrapper0, intArray1[4], intArray1, intWrapper0);
      assertEquals("4", intWrapper0.toString());
      assertEquals(4.0F, intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[6];
      integratedComposition0.compress(intArray0, intWrapper0, (-84), intArray1, intWrapper0);
      assertEquals(1.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(1, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      integratedComposition0.compress(intArray0, intWrapper0, (-7), intArray0, intWrapper1);
      assertEquals((byte)1, intWrapper1.byteValue());
      assertEquals("1", intWrapper1.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper(33554431);
      // Undeclared exception!
      try { 
        integratedComposition0.uncompress((int[]) null, intWrapper0, 33554431, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedBinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[3];
      intArray0[0] = 531;
      intArray0[1] = (-1327);
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        integratedComposition0.uncompress(intArray0, intWrapper0, 531, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntegratedComposition integratedComposition0 = new IntegratedComposition((IntegratedIntegerCODEC) null, (IntegratedIntegerCODEC) null);
      // Undeclared exception!
      try { 
        integratedComposition0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(integratedVariableByte0, integratedVariableByte0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(1175);
      // Undeclared exception!
      try { 
        integratedComposition0.compress(intArray0, intWrapper0, Integer.MIN_VALUE, intArray0, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(integratedVariableByte0, (IntegratedIntegerCODEC) null);
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        integratedComposition0.compress(intArray0, intWrapper0, 2138603656, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-71039936 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        integratedComposition0.compress(intArray0, intWrapper0, 1200, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.differential.XorBinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedComposition0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      XorBinaryPacking xorBinaryPacking0 = new XorBinaryPacking();
      IntegratedComposition integratedComposition0 = new IntegratedComposition(xorBinaryPacking0, xorBinaryPacking0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedComposition0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals((short)0, intWrapper0.shortValue());
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
  }
}
