/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:43:38 GMT 2024
 */

package me.lemire.integercompression.differential;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.differential.IntegratedVariableByte;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntegratedVariableByte_ESTest extends IntegratedVariableByte_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[5];
      intArray0[4] = (-1);
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        integratedVariableByte0.headlessUncompress(intArray0, intWrapper0, 1925, intArray0, intWrapper0, 1342177282, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(2);
      integratedVariableByte0.headlessUncompress(intArray0, intWrapper0, 2, intArray0, intWrapper0, (-328), intWrapper0);
      assertEquals((byte)2, intWrapper0.byteValue());
      assertEquals(2L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[23];
      intArray0[3] = (int) (byte) (-128);
      integratedVariableByte0.headlessCompress(intArray0, intWrapper0, 15, intArray0, intWrapper0, intWrapper0);
      assertEquals(20.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(20, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[8];
      byteArray0[1] = (byte) (-48);
      byteArray0[4] = (byte)98;
      // Undeclared exception!
      try { 
        integratedVariableByte0.uncompress(byteArray0, intWrapper0, 1021, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(1);
      byte[] byteArray0 = new byte[8];
      byteArray0[2] = (byte)71;
      integratedVariableByte0.uncompress(byteArray0, intWrapper0, 1, intArray0, intWrapper0);
      assertEquals(8.0, intWrapper0.doubleValue(), 0.01);
      assertArrayEquals(new int[] {0, 9088, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)62;
      // Undeclared exception!
      try { 
        integratedVariableByte0.uncompress(byteArray0, intWrapper0, 1, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 3
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      intArray0[3] = (-939);
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.uncompress(intArray0, intWrapper0, 2516, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedVariableByte0.uncompress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      assertEquals(1L, intWrapper0.longValue());
      assertEquals(1, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedVariableByte0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper1, 2146289274, (byte[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[14];
      integratedVariableByte0.compress(intArray0, intWrapper0, (-1922), byteArray0, intWrapper0);
      assertEquals((-1922L), intWrapper0.longValue());
      assertEquals((-1922.0F), intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = new IntWrapper(1);
      integratedVariableByte0.compress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper1, 31, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntWrapper intWrapper0 = new IntWrapper(3228);
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress((int[]) null, intWrapper0, (-2130165230), (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.IntBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      ByteBuffer byteBuffer0 = integratedVariableByte0.makeBuffer(788);
      assertEquals(788, byteBuffer0.limit());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      byte[] byteArray0 = new byte[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[4];
      intArray0[0] = 14;
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper0, 14, byteArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        integratedVariableByte0.uncompress((int[]) null, intWrapper0, 1, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      // Undeclared exception!
      try { 
        integratedVariableByte0.uncompress((byte[]) null, intWrapper0, 1, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      // Undeclared exception!
      try { 
        integratedVariableByte0.makeBuffer((-2138079361));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-2138079361 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      // Undeclared exception!
      try { 
        integratedVariableByte0.headlessUncompress(intArray0, (IntWrapper) null, 1925, intArray0, (IntWrapper) null, 1, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntWrapper intWrapper0 = new IntWrapper((-876));
      // Undeclared exception!
      try { 
        integratedVariableByte0.headlessCompress((int[]) null, intWrapper0, (-876), (int[]) null, intWrapper0, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedVariableByte0.compress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.headlessCompress(intArray0, intWrapper0, (-1), intArray0, intWrapper0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-8 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.headlessCompress(intArray0, intWrapper0, (byte) (-127), intArray0, intWrapper0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -128 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper0, 1073741824, intArray0, intWrapper0);
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper0, (-3293), intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-26344 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[3];
      byteArray0[2] = (byte) (-98);
      integratedVariableByte0.uncompress(byteArray0, intWrapper0, 1, intArray0, intWrapper0);
      integratedVariableByte0.headlessUncompress(intArray0, intWrapper0, 1, intArray0, intWrapper0, 0, intWrapper0);
      assertEquals(4.0F, intWrapper0.floatValue(), 0.01F);
      assertArrayEquals(new int[] {491520, 0, 0, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      integratedVariableByte0.compress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      integratedVariableByte0.headlessUncompress(intArray0, intWrapper1, 1, intArray0, intWrapper1, 1, intWrapper1);
      assertEquals(1L, intWrapper1.longValue());
      assertArrayEquals(new int[] {0, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      integratedVariableByte0.compress(intArray0, intWrapper0, 3, intArray0, intWrapper0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.headlessCompress(intArray0, intWrapper1, 3, intArray0, intWrapper0, intWrapper1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[3];
      byteArray0[2] = (byte) (-98);
      integratedVariableByte0.uncompress(byteArray0, intWrapper0, 1, intArray0, intWrapper0);
      integratedVariableByte0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0, intWrapper0);
      assertEquals((byte)2, intWrapper0.byteValue());
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      integratedVariableByte0.headlessCompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, intWrapper0);
      assertArrayEquals(new int[] {0, 0, 0, 0}, intArray0);
      assertEquals(0, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[16];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[4];
      byteArray0[3] = (byte) (-127);
      integratedVariableByte0.uncompress(byteArray0, intWrapper0, 1, intArray0, intWrapper0);
      assertEquals((short)5, intWrapper0.shortValue());
      assertEquals(5, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-98);
      integratedVariableByte0.uncompress(byteArray0, intWrapper0, 1, intArray0, intWrapper0);
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(2, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedVariableByte0.uncompress(intArray0, intWrapper0, (-1845), intArray0, intWrapper0);
      assertEquals((-1845.0F), intWrapper0.floatValue(), 0.01F);
      assertEquals((-1845), intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[14];
      intArray0[6] = 3279;
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[9];
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper0, 3279, byteArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(2);
      integratedVariableByte0.compress(intArray0, intWrapper0, 2, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(2);
      byte[] byteArray0 = new byte[9];
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper1, 2, byteArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[14];
      IntWrapper intWrapper0 = new IntWrapper(0);
      byte[] byteArray0 = new byte[9];
      integratedVariableByte0.compress(intArray0, intWrapper0, 0, byteArray0, intWrapper0);
      assertEquals((short)0, intWrapper0.shortValue());
      assertEquals(0, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(2);
      byte[] byteArray0 = new byte[9];
      integratedVariableByte0.compress(intArray0, intWrapper0, 2, byteArray0, intWrapper0);
      assertEquals((short)6, intWrapper0.shortValue());
      assertEquals(6L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      integratedVariableByte0.compress(intArray0, intWrapper0, 3, intArray0, intWrapper0);
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper1, 3, intArray0, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(2);
      integratedVariableByte0.compress(intArray0, intWrapper0, 2, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(2);
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper1, 2, intArray0, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      integratedVariableByte0.compress(intArray0, intWrapper0, 3, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      byte[] byteArray0 = new byte[8];
      // Undeclared exception!
      try { 
        integratedVariableByte0.compress(intArray0, intWrapper1, 27, byteArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      int[] intArray0 = new int[5];
      integratedVariableByte0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0}, intArray0);
      assertEquals("0", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      String string0 = integratedVariableByte0.toString();
      assertEquals("IntegratedVariableByte", string0);
  }
}
