/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:35:58 GMT 2024
 */

package me.lemire.integercompression.differential;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.differential.IntegratedBinaryPacking;
import me.lemire.integercompression.differential.IntegratedIntCompressor;
import me.lemire.integercompression.differential.IntegratedVariableByte;
import me.lemire.integercompression.differential.SkippableIntegratedComposition;
import me.lemire.integercompression.differential.SkippableIntegratedIntegerCODEC;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntegratedIntCompressor_ESTest extends IntegratedIntCompressor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor(221, integratedVariableByte0);
      int[] intArray0 = new int[1];
      intArray0[0] = 221;
      int[] intArray1 = integratedIntCompressor0.uncompress(intArray0);
      int[] intArray2 = integratedIntCompressor0.compress(intArray1);
      assertEquals(12, intArray2.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor((-1603), integratedBinaryPacking0);
      int[] intArray0 = new int[3];
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      integratedIntCompressor0.codec = (SkippableIntegratedIntegerCODEC) skippableIntegratedComposition0;
      int[] intArray1 = integratedIntCompressor0.uncompress(intArray0);
      assertEquals(0, intArray1.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor(1474, (SkippableIntegratedIntegerCODEC) null);
      // Undeclared exception!
      try { 
        integratedIntCompressor0.uncompress((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedIntCompressor", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor((-1439), integratedBinaryPacking0);
      int[] intArray0 = new int[1];
      intArray0[0] = (-1439);
      // Undeclared exception!
      try { 
        integratedIntCompressor0.uncompress(intArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -1439
         //
         verifyException("me.lemire.integercompression.differential.IntegratedIntCompressor", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor(221, (SkippableIntegratedIntegerCODEC) null);
      int[] intArray0 = new int[2];
      intArray0[0] = 221;
      intArray0[1] = 221;
      // Undeclared exception!
      try { 
        integratedIntCompressor0.uncompress(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.differential.IntegratedBitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor((-1603), integratedBinaryPacking0);
      int[] intArray0 = new int[3];
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      integratedIntCompressor0.codec = (SkippableIntegratedIntegerCODEC) skippableIntegratedComposition0;
      skippableIntegratedComposition0.F2 = integratedIntCompressor0.codec;
      // Undeclared exception!
      try { 
        integratedIntCompressor0.compress(intArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Your input is too poorly compressible with the current codec : me.lemire.integercompression.differential.IntegratedBinaryPacking@0000000001 + me.lemire.integercompression.differential.SkippableIntegratedComposition@0000000006
         //
         verifyException("me.lemire.integercompression.differential.IntegratedIntCompressor", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor((-2555), (SkippableIntegratedIntegerCODEC) null);
      // Undeclared exception!
      try { 
        integratedIntCompressor0.compress((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedIntCompressor", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor(0, integratedVariableByte0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntegratedIntCompressor integratedIntCompressor0 = new IntegratedIntCompressor((-1603), integratedBinaryPacking0);
      int[] intArray0 = new int[3];
      // Undeclared exception!
      try { 
        integratedIntCompressor0.uncompress(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1 out of bounds for length 0
         //
         verifyException("me.lemire.integercompression.differential.IntegratedVariableByte", e);
      }
  }
}
