/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:39:36 GMT 2024
 */

package me.lemire.integercompression.differential;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.differential.IntegratedBinaryPacking;
import me.lemire.integercompression.differential.IntegratedVariableByte;
import me.lemire.integercompression.differential.SkippableIntegratedComposition;
import me.lemire.integercompression.differential.SkippableIntegratedIntegerCODEC;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SkippableIntegratedComposition_ESTest extends SkippableIntegratedComposition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = new IntWrapper((-388));
      IntWrapper intWrapper1 = new IntWrapper(95);
      skippableIntegratedComposition0.headlessUncompress(intArray0, intWrapper1, (-1698), intArray0, intWrapper1, 0, intWrapper0);
      assertEquals((short)96, intWrapper1.shortValue());
      assertEquals((-388L), intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      skippableIntegratedComposition0.headlessUncompress(intArray0, intWrapper0, 288, (int[]) null, intWrapper0, 0, intWrapper0);
      assertEquals((byte)1, intWrapper0.byteValue());
      assertEquals(1L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      SkippableIntegratedComposition skippableIntegratedComposition1 = new SkippableIntegratedComposition(skippableIntegratedComposition0, integratedBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper(64);
      skippableIntegratedComposition1.headlessUncompress((int[]) null, intWrapper0, (-47), (int[]) null, intWrapper0, (-229), intWrapper0);
      assertEquals(65L, intWrapper0.longValue());
      assertEquals((short)65, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper(1856);
      IntWrapper intWrapper1 = new IntWrapper(0);
      skippableIntegratedComposition0.headlessUncompress((int[]) null, intWrapper0, (-174), (int[]) null, intWrapper1, (-626), intWrapper1);
      assertEquals((short)1857, intWrapper0.shortValue());
      assertEquals("1857", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper(14);
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedVariableByte0, (SkippableIntegratedIntegerCODEC) null);
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper1, intWrapper1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper(1);
      int[] intArray0 = new int[8];
      int[] intArray1 = new int[5];
      skippableIntegratedComposition0.headlessCompress(intArray1, intWrapper0, 14, intArray0, intWrapper0, intWrapper0);
      assertEquals((byte)2, intWrapper0.byteValue());
      assertEquals("2", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper(1);
      int[] intArray0 = new int[8];
      IntWrapper intWrapper1 = new IntWrapper(1);
      skippableIntegratedComposition0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0, intWrapper1);
      assertEquals("2", intWrapper0.toString());
      assertEquals(2, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      SkippableIntegratedComposition skippableIntegratedComposition1 = new SkippableIntegratedComposition(skippableIntegratedComposition0, skippableIntegratedComposition0);
      skippableIntegratedComposition1.F1 = skippableIntegratedComposition0.F1;
      String string0 = skippableIntegratedComposition1.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntWrapper intWrapper0 = new IntWrapper(738);
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.headlessUncompress((int[]) null, intWrapper0, 738, (int[]) null, intWrapper0, 738, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.differential.IntegratedBinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      int[] intArray0 = new int[1];
      intArray0[0] = 55;
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.headlessUncompress(intArray0, intWrapper0, (-925), intArray0, intWrapper0, 55, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.differential.IntegratedBitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = new IntWrapper((-388));
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.headlessUncompress(intArray0, intWrapper0, (-1698), intArray0, intWrapper0, 0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -387 out of bounds for length 5
         //
         verifyException("me.lemire.integercompression.differential.IntegratedBinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedVariableByte0, (SkippableIntegratedIntegerCODEC) null);
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int[] intArray0 = new int[2];
      intArray0[0] = (-1235);
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper(14);
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedVariableByte0, (SkippableIntegratedIntegerCODEC) null);
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper1, intWrapper1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper(5);
      IntegratedVariableByte integratedVariableByte0 = new IntegratedVariableByte();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedVariableByte0, integratedVariableByte0);
      int[] intArray0 = new int[7];
      intArray0[5] = 5;
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-8 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper(1);
      SkippableIntegratedComposition skippableIntegratedComposition1 = new SkippableIntegratedComposition(integratedBinaryPacking0, skippableIntegratedComposition0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        skippableIntegratedComposition1.headlessCompress(intArray0, intWrapper1, 1, intArray0, intWrapper0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      int[] intArray0 = new int[13];
      IntWrapper intWrapper0 = new IntWrapper(0);
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      skippableIntegratedComposition0.headlessUncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, 0, intWrapper0);
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(5);
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      SkippableIntegratedComposition skippableIntegratedComposition1 = new SkippableIntegratedComposition(skippableIntegratedComposition0, skippableIntegratedComposition0);
      skippableIntegratedComposition1.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0, intWrapper0);
      assertEquals(6.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(6, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition((SkippableIntegratedIntegerCODEC) null, (SkippableIntegratedIntegerCODEC) null);
      // Undeclared exception!
      try { 
        skippableIntegratedComposition0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      IntegratedBinaryPacking integratedBinaryPacking0 = new IntegratedBinaryPacking();
      SkippableIntegratedComposition skippableIntegratedComposition0 = new SkippableIntegratedComposition(integratedBinaryPacking0, integratedBinaryPacking0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      skippableIntegratedComposition0.headlessCompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, intWrapper0);
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(0, intWrapper0.get());
  }
}
