/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:59:39 GMT 2024
 */

package com.kamikaze.pfordelta;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.kamikaze.pfordelta.PForDeltaUnpack128;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PForDeltaUnpack128_ESTest extends PForDeltaUnpack128_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[] intArray0 = new int[65];
      int[] intArray1 = new int[11];
      intArray1[1] = 10;
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray1, 10);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 11 out of bounds for length 11
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[9];
      intArray0[1] = (-2032);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray0, 8);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[6];
      int[] intArray1 = new int[8];
      intArray1[1] = (-1353);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray1, 7);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[9];
      int[] intArray1 = new int[8];
      intArray1[1] = (-223);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray1, 6);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[1] = (-477);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray0, 5);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 7 out of bounds for length 7
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[1] = (-401);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray0, 4);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[133];
      int[] intArray1 = new int[9];
      intArray1[1] = (-3016);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray1, 3);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[1] = (-600);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray0, 2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[1] = (-15);
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack(intArray0, intArray0, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        PForDeltaUnpack128.unpack((int[]) null, (int[]) null, 28);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.kamikaze.pfordelta.PForDeltaUnpack128", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 5);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[165];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 28);
      assertEquals(165, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int[] intArray0 = new int[4];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 27);
      assertArrayEquals(new int[] {0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int[] intArray0 = new int[65];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 26);
      assertEquals(65, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int[] intArray0 = new int[9];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 25);
      assertEquals(9, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int[] intArray0 = new int[18];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 24);
      assertEquals(18, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      int[] intArray0 = new int[39];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 23);
      assertEquals(39, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int[] intArray0 = new int[17];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 22);
      assertEquals(17, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int[] intArray0 = new int[67];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 21);
      assertEquals(67, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int[] intArray0 = new int[165];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 20);
      assertEquals(165, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      int[] intArray0 = new int[64];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 19);
      assertEquals(64, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      int[] intArray0 = new int[5];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 18);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      int[] intArray0 = new int[39];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 17);
      assertEquals(39, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int[] intArray0 = new int[165];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 16);
      assertEquals(165, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int[] intArray0 = new int[39];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 15);
      assertEquals(39, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      int[] intArray0 = new int[22];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 14);
      assertEquals(22, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 13);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 12);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int[] intArray0 = new int[146];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 11);
      assertEquals(146, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 10);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int[] intArray0 = new int[146];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 9);
      assertEquals(146, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int[] intArray0 = new int[165];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 8);
      assertEquals(165, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      int[] intArray0 = new int[146];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 7);
      assertEquals(146, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 6);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      int[] intArray0 = new int[146];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 4);
      assertEquals(146, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 3);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 2);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      int[] intArray0 = new int[133];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 1);
      assertEquals(133, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      int[] intArray0 = new int[7];
      PForDeltaUnpack128.unpack(intArray0, intArray0, (-477));
      assertArrayEquals(new int[] {0, 0, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      PForDeltaUnpack128 pForDeltaUnpack128_0 = new PForDeltaUnpack128();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      int[] intArray0 = new int[149];
      PForDeltaUnpack128.unpack(intArray0, intArray0, 0);
      assertEquals(149, intArray0.length);
  }
}
