/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 03:59:07 GMT 2024
 */

package dk.tbsalling.aismessages;

import java.io.InputStream;
import java.io.PipedInputStream;
import java.util.function.Consumer;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import static org.evosuite.shaded.org.mockito.Mockito.mock;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import org.junit.Test;
import org.junit.runner.RunWith;

import dk.tbsalling.aismessages.ais.messages.AISMessage;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AISInputStreamReader_ESTest extends AISInputStreamReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      AISInputStreamReader aISInputStreamReader0 = new AISInputStreamReader((InputStream) null, consumer0);
      aISInputStreamReader0.requestStop();
      boolean boolean0 = aISInputStreamReader0.isStopRequested();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      AISInputStreamReader aISInputStreamReader0 = new AISInputStreamReader(pipedInputStream0, (Consumer<? super AISMessage>) null);
      boolean boolean0 = aISInputStreamReader0.isStopRequested();
      assertFalse(boolean0);
  }
}
