/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:18:56 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.DataLinkManagement;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DataLinkManagement_ESTest extends DataLinkManagement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[1];
      DataLinkManagement dataLinkManagement0 = null;
      try {
        dataLinkManagement0 = new DataLinkManagement(nMEAMessageArray0, "01010");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[9];
      DataLinkManagement dataLinkManagement0 = null;
      try {
        dataLinkManagement0 = new DataLinkManagement(nMEAMessageArray0, "010100");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Message of type DataLinkManagement should be 72-160 bits long; not 6.
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.DataLinkManagement", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[0];
      DataLinkManagement dataLinkManagement0 = null;
      try {
        dataLinkManagement0 = new DataLinkManagement(nMEAMessageArray0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.AISMessage", e);
      }
  }
}
