/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:51:05 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.GNSSBinaryBroadcastMessage;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GNSSBinaryBroadcastMessage_ESTest extends GNSSBinaryBroadcastMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[16];
      GNSSBinaryBroadcastMessage gNSSBinaryBroadcastMessage0 = null;
      try {
        gNSSBinaryBroadcastMessage0 = new GNSSBinaryBroadcastMessage(nMEAMessageArray0, "010001");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Message of type GNSSBinaryBroadcastMessage should be 80-816 bits long; not 6.
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.GNSSBinaryBroadcastMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[0];
      GNSSBinaryBroadcastMessage gNSSBinaryBroadcastMessage0 = null;
      try {
        gNSSBinaryBroadcastMessage0 = new GNSSBinaryBroadcastMessage(nMEAMessageArray0, "100101");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.AISMessage", e);
      }
  }
}
