/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:44:38 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.GroupAssignmentCommand;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GroupAssignmentCommand_ESTest extends GroupAssignmentCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[6];
      GroupAssignmentCommand groupAssignmentCommand0 = null;
      try {
        groupAssignmentCommand0 = new GroupAssignmentCommand(nMEAMessageArray0, "010111");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Message of type GroupAssignmentCommand should be at exactly 160 bits long; not 6.
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.GroupAssignmentCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[0];
      GroupAssignmentCommand groupAssignmentCommand0 = null;
      try {
        groupAssignmentCommand0 = new GroupAssignmentCommand(nMEAMessageArray0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.AISMessage", e);
      }
  }
}
