/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 12:55:38 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.BinaryPacking;
import me.lemire.integercompression.IntWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BinaryPacking_ESTest extends BinaryPacking_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[1];
      intArray0[0] = 524287;
      // Undeclared exception!
      try { 
        binaryPacking0.headlessUncompress(intArray0, intWrapper0, 524287, intArray0, intWrapper0, 524287);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 32
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[6];
      int[] intArray1 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        binaryPacking0.headlessUncompress(intArray1, intWrapper0, 0, intArray0, intWrapper0, 1572);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 32
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray1 = new int[8];
      binaryPacking0.uncompress(intArray0, intWrapper0, 99, intArray1, intWrapper0);
      assertEquals(1.0F, intWrapper0.floatValue(), 0.01F);
      assertEquals(1, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(1);
      IntWrapper intWrapper1 = new IntWrapper(96);
      binaryPacking0.uncompress(intArray0, intWrapper0, (-806), intArray0, intWrapper1);
      assertEquals((short)2, intWrapper0.shortValue());
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[1];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      intWrapper0.add(Integer.MAX_VALUE);
      BinaryPacking binaryPacking0 = new BinaryPacking();
      IntWrapper intWrapper1 = new IntWrapper(1064);
      // Undeclared exception!
      try { 
        binaryPacking0.headlessCompress(intArray0, intWrapper0, 902, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -2147483617 out of bounds for length 1
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[3];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      intWrapper0.add(2147483646);
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray1 = new int[8];
      // Undeclared exception!
      try { 
        binaryPacking0.headlessCompress(intArray0, intWrapper0, 33554431, intArray1, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -2147483618 out of bounds for length 3
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        binaryPacking0.compress(intArray0, intWrapper1, 128, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        binaryPacking0.compress((int[]) null, intWrapper0, (-1752), (int[]) null, intWrapper1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.BinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[7];
      // Undeclared exception!
      try { 
        binaryPacking0.compress((int[]) null, intWrapper0, 4194303, intArray0, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(1);
      binaryPacking0.compress(intArray0, intWrapper0, (-1768), intArray0, intWrapper0);
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
      assertArrayEquals(new int[] {0, (-1760)}, intArray0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        binaryPacking0.uncompress(intArray0, (IntWrapper) null, 1216, intArray0, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.BinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[2];
      intArray0[0] = 2106;
      intArray0[1] = (-627);
      // Undeclared exception!
      try { 
        binaryPacking0.uncompress(intArray0, intWrapper0, 2106, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      IntWrapper intWrapper0 = new IntWrapper(0);
      intWrapper0.add((-888));
      int[] intArray0 = new int[1];
      // Undeclared exception!
      try { 
        binaryPacking0.uncompress(intArray0, intWrapper0, 1668, (int[]) null, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -888 out of bounds for length 1
         //
         verifyException("me.lemire.integercompression.BinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      BinaryPacking binaryPacking0 = new BinaryPacking();
      // Undeclared exception!
      try { 
        binaryPacking0.headlessUncompress((int[]) null, intWrapper0, 2106, (int[]) null, intWrapper0, 2106);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.BinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int[] intArray0 = new int[3];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      BinaryPacking binaryPacking0 = new BinaryPacking();
      IntWrapper intWrapper1 = new IntWrapper(2147483646);
      // Undeclared exception!
      try { 
        binaryPacking0.headlessUncompress(intArray0, intWrapper0, 13, intArray0, intWrapper1, (-2003));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // fromIndex(2147483646) > toIndex(-2147483618)
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[1];
      intArray0[0] = 75;
      // Undeclared exception!
      try { 
        binaryPacking0.headlessUncompress(intArray0, intWrapper0, 75, intArray0, intWrapper0, 75);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      binaryPacking0.headlessUncompress((int[]) null, intWrapper0, 0, (int[]) null, intWrapper0, 0);
      assertEquals(0, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[6];
      binaryPacking0.uncompress(intArray0, (IntWrapper) null, 0, intArray0, (IntWrapper) null);
      assertEquals(6, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      IntWrapper intWrapper0 = new IntWrapper(32);
      // Undeclared exception!
      try { 
        binaryPacking0.headlessCompress((int[]) null, intWrapper0, 32, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper((-1));
      binaryPacking0.headlessCompress(intArray0, intWrapper0, 8, intArray0, intWrapper0);
      assertEquals((-1), intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(1);
      binaryPacking0.compress(intArray0, intWrapper0, (-1), intArray0, intWrapper0);
      assertEquals((short)1, intWrapper0.shortValue());
      assertEquals(1, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BinaryPacking binaryPacking0 = new BinaryPacking();
      String string0 = binaryPacking0.toString();
      assertEquals("BinaryPacking", string0);
  }
}
