/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:04:28 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.Composition;
import me.lemire.integercompression.DeltaZigzagBinaryPacking;
import me.lemire.integercompression.DeltaZigzagVariableByte;
import me.lemire.integercompression.FastPFOR;
import me.lemire.integercompression.GroupSimple9;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.IntegerCODEC;
import me.lemire.integercompression.JustCopy;
import me.lemire.integercompression.Kamikaze;
import me.lemire.integercompression.NewPFDS9;
import me.lemire.integercompression.OptPFD;
import me.lemire.integercompression.OptPFDS16;
import me.lemire.integercompression.Simple16;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Composition_ESTest extends Composition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Composition composition0 = new Composition((IntegerCODEC) null, (IntegerCODEC) null);
      Kamikaze kamikaze0 = new Kamikaze();
      composition0.F1 = (IntegerCODEC) kamikaze0;
      // Undeclared exception!
      try { 
        composition0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, deltaZigzagBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[2];
      int[] intArray1 = new int[4];
      composition0.uncompress(intArray0, intWrapper0, 33, intArray1, intWrapper0);
      assertEquals("2", intWrapper0.toString());
      assertEquals(2.0F, intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, deltaZigzagBinaryPacking0);
      int[] intArray0 = new int[9];
      IntWrapper intWrapper0 = new IntWrapper(1);
      composition0.uncompress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      assertEquals("2", intWrapper0.toString());
      assertEquals(2, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OptPFD optPFD0 = new OptPFD();
      Composition composition0 = new Composition(optPFD0, optPFD0);
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(77);
      // Undeclared exception!
      try { 
        composition0.uncompress(intArray0, intWrapper0, (-2182), (int[]) null, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 77 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.OptPFD", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, deltaZigzagBinaryPacking0);
      int[] intArray0 = new int[9];
      IntWrapper intWrapper0 = new IntWrapper((-2335));
      int[] intArray1 = new int[8];
      // Undeclared exception!
      try { 
        composition0.compress(intArray0, intWrapper0, 127, intArray1, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -2335 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.Composition", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      Composition composition0 = new Composition(optPFDS16_0, optPFDS16_0);
      int[] intArray0 = new int[9];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[6];
      composition0.compress(intArray0, intWrapper0, (-1653), intArray1, intWrapper0);
      assertEquals((byte)2, intWrapper0.byteValue());
      assertEquals(2.0F, intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      NewPFDS9 newPFDS9_0 = new NewPFDS9();
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, newPFDS9_0);
      int[] intArray0 = new int[11];
      IntWrapper intWrapper0 = new IntWrapper(47);
      IntWrapper intWrapper1 = new IntWrapper(0);
      composition0.compress(intArray0, intWrapper0, 47, intArray0, intWrapper1);
      assertEquals("1", intWrapper1.toString());
      assertEquals(1.0, intWrapper1.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      NewPFDS9 newPFDS9_0 = new NewPFDS9();
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, newPFDS9_0);
      int[] intArray0 = new int[9];
      IntWrapper intWrapper0 = new IntWrapper(47);
      IntWrapper intWrapper1 = new IntWrapper(0);
      composition0.uncompress(intArray0, intWrapper1, 47, intArray0, intWrapper0);
      assertEquals((byte)2, intWrapper1.byteValue());
      assertEquals(2.0F, intWrapper1.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GroupSimple9 groupSimple9_0 = new GroupSimple9();
      Composition composition0 = new Composition(groupSimple9_0, groupSimple9_0);
      int[] intArray0 = new int[5];
      intArray0[1] = 2089;
      intArray0[2] = (-1935);
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        composition0.uncompress(intArray0, intWrapper0, 4707, intArray0, intWrapper0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Wrong code: 255
         //
         verifyException("me.lemire.integercompression.GroupSimple9", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      IntWrapper intWrapper0 = new IntWrapper((-1));
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, deltaZigzagBinaryPacking0);
      int[] intArray0 = new int[4];
      intArray0[1] = 2381;
      intArray0[2] = (-1);
      intWrapper0.increment();
      // Undeclared exception!
      try { 
        composition0.uncompress(intArray0, intWrapper0, 2381, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, deltaZigzagBinaryPacking0);
      IntWrapper intWrapper0 = new IntWrapper((-815));
      // Undeclared exception!
      try { 
        composition0.compress((int[]) null, intWrapper0, (-815), (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.DeltaZigzagBinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      Composition composition0 = new Composition(deltaZigzagVariableByte0, deltaZigzagVariableByte0);
      IntWrapper intWrapper0 = new IntWrapper((-28));
      // Undeclared exception!
      try { 
        composition0.compress((int[]) null, intWrapper0, (-28), (int[]) null, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-137 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      JustCopy justCopy0 = new JustCopy();
      Composition composition0 = new Composition(simple16_0, justCopy0);
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      composition0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0, intWrapper0.intValue());
      assertEquals("0", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      Composition composition0 = new Composition(fastPFOR0, fastPFOR0);
      IntWrapper intWrapper0 = new IntWrapper(65536);
      // Undeclared exception!
      try { 
        composition0.uncompress((int[]) null, intWrapper0, 256, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      IntWrapper intWrapper0 = new IntWrapper(0);
      Composition composition0 = new Composition(deltaZigzagBinaryPacking0, deltaZigzagBinaryPacking0);
      int[] intArray0 = new int[0];
      composition0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      Composition composition0 = new Composition(fastPFOR0, fastPFOR0);
      String string0 = composition0.toString();
      assertNotNull(string0);
  }
}
