/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:08:06 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.DeltaZigzagEncoding;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DeltaZigzagEncoding_ESTest extends DeltaZigzagEncoding_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DeltaZigzagEncoding.Decoder deltaZigzagEncoding_Decoder0 = new DeltaZigzagEncoding.Decoder(748);
      int[] intArray0 = new int[4];
      // Undeclared exception!
      try { 
        deltaZigzagEncoding_Decoder0.decodeArray(intArray0, 1, 177);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Decoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeltaZigzagEncoding.Decoder deltaZigzagEncoding_Decoder0 = new DeltaZigzagEncoding.Decoder(1011);
      int int0 = deltaZigzagEncoding_Decoder0.decodeInt((-3593));
      assertEquals((-2147480841), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder((-3642));
      int[] intArray0 = deltaZigzagEncoding_Encoder0.encodeArray((int[]) null, (-1634), (-2585), (int[]) null);
      assertNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder(0);
      int[] intArray0 = new int[2];
      int[] intArray1 = new int[5];
      int[] intArray2 = deltaZigzagEncoding_Encoder0.encodeArray(intArray1, (-2307), (-2307), intArray0);
      assertEquals(2, intArray2.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[7];
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder(1);
      // Undeclared exception!
      try { 
        deltaZigzagEncoding_Encoder0.encodeArray(intArray0, (-1506), 31);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1506 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Encoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder(0);
      int[] intArray0 = new int[5];
      intArray0[4] = (-796);
      int[] intArray1 = deltaZigzagEncoding_Encoder0.encodeArray(intArray0);
      assertArrayEquals(new int[] {0, 0, 0, 0, 1591}, intArray1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DeltaZigzagEncoding.Decoder deltaZigzagEncoding_Decoder0 = new DeltaZigzagEncoding.Decoder(0);
      deltaZigzagEncoding_Decoder0.setContextValue(31);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder(0);
      int[] intArray0 = new int[3];
      int[] intArray1 = deltaZigzagEncoding_Encoder0.encodeArray(intArray0, 0, 0);
      assertEquals(0, intArray1.length);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder(1);
      int int0 = deltaZigzagEncoding_Encoder0.encodeInt(905);
      assertEquals(1808, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder(0);
      int[] intArray0 = new int[2];
      int[] intArray1 = deltaZigzagEncoding_Encoder0.encodeArray(intArray0, 0, 0, intArray0, (-1121));
      assertSame(intArray0, intArray1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeltaZigzagEncoding.Decoder deltaZigzagEncoding_Decoder0 = new DeltaZigzagEncoding.Decoder(0);
      int[] intArray0 = new int[2];
      int[] intArray1 = deltaZigzagEncoding_Decoder0.decodeArray(intArray0, 0, (-2707), intArray0, 0);
      assertSame(intArray0, intArray1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeltaZigzagEncoding.Context deltaZigzagEncoding_Context0 = new DeltaZigzagEncoding.Context((-3593));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeltaZigzagEncoding deltaZigzagEncoding0 = new DeltaZigzagEncoding();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DeltaZigzagEncoding.Encoder deltaZigzagEncoding_Encoder0 = new DeltaZigzagEncoding.Encoder(0);
      int int0 = deltaZigzagEncoding_Encoder0.getContextValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DeltaZigzagEncoding.Decoder deltaZigzagEncoding_Decoder0 = new DeltaZigzagEncoding.Decoder(0);
      int[] intArray0 = new int[2];
      int[] intArray1 = deltaZigzagEncoding_Decoder0.decodeArray(intArray0);
      assertArrayEquals(new int[] {0, 0}, intArray1);
      assertNotSame(intArray1, intArray0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DeltaZigzagEncoding.Decoder deltaZigzagEncoding_Decoder0 = new DeltaZigzagEncoding.Decoder(0);
      int[] intArray0 = new int[2];
      int[] intArray1 = deltaZigzagEncoding_Decoder0.decodeArray(intArray0, 0, 0);
      assertEquals(0, intArray1.length);
  }
}
