/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 12:53:22 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import me.lemire.integercompression.DeltaZigzagVariableByte;
import me.lemire.integercompression.IntWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DeltaZigzagVariableByte_ESTest extends DeltaZigzagVariableByte_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[5];
      intArray0[0] = (-478);
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.uncompress(intArray0, intWrapper0, 1693, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper((-3332));
      deltaZigzagVariableByte0.uncompress(intArray0, intWrapper0, (-3332), intArray0, intWrapper0);
      assertEquals((-6664.0F), intWrapper0.floatValue(), 0.01F);
      assertEquals((byte) (-8), intWrapper0.byteValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.uncompress(intArray0, intWrapper0, 1206, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[10];
      IntWrapper intWrapper0 = new IntWrapper(1);
      int[] intArray1 = new int[4];
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 2021, intArray1, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 10 out of bounds for length 10
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.makeBuffer((-54));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-54 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, (IntWrapper) null, 9, intArray0, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(1);
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper1, 1, intArray0, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[10];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper0, (-20), intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-97 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      IntWrapper intWrapper0 = new IntWrapper(1);
      int[] intArray0 = new int[2];
      intArray0[1] = 1;
      deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper1, 3, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int[] intArray0 = new int[10];
      IntWrapper intWrapper0 = new IntWrapper(1);
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(1);
      deltaZigzagVariableByte0.uncompress(intArray0, intWrapper1, 1, intArray0, intWrapper0);
      assertEquals(4.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(2.0, intWrapper1.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int[] intArray0 = new int[16];
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      IntWrapper intWrapper0 = new IntWrapper(5);
      deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 5, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(5);
      intWrapper1.increment();
      deltaZigzagVariableByte0.compress(intArray0, intWrapper1, 5, intArray0, intWrapper0);
      assertEquals((short)15, intWrapper0.shortValue());
      
      deltaZigzagVariableByte0.compress(intArray0, intWrapper1, 5, intArray0, intWrapper1);
      assertEquals("20", intWrapper1.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[4];
      intArray0[0] = (-478);
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 1013, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[4];
      intArray0[3] = (-676);
      IntWrapper intWrapper0 = new IntWrapper(3);
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 14, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[1];
      intArray0[0] = 1497;
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 1497, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[4];
      intArray0[1] = 5537;
      intArray0[2] = (-3349);
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 5537, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int[] intArray0 = new int[16];
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      IntWrapper intWrapper0 = new IntWrapper(5);
      intWrapper0.increment();
      deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 5, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(5);
      deltaZigzagVariableByte0.compress(intArray0, intWrapper1, 5, intArray0, intWrapper0);
      // Undeclared exception!
      try { 
        deltaZigzagVariableByte0.compress(intArray0, intWrapper1, 22, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 16 out of bounds for length 16
         //
         verifyException("me.lemire.integercompression.DeltaZigzagVariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      deltaZigzagVariableByte0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0, 0, 0}, intArray0);
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      ByteBuffer byteBuffer0 = deltaZigzagVariableByte0.makeBuffer(1);
      assertEquals(1, byteBuffer0.limit());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DeltaZigzagVariableByte deltaZigzagVariableByte0 = new DeltaZigzagVariableByte();
      String string0 = deltaZigzagVariableByte0.toString();
      assertEquals("DeltaZigzagVariableByte", string0);
  }
}
