/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:31:03 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.DeltaZigzagBinaryPacking;
import me.lemire.integercompression.IntWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DeltaZigzagBinaryPacking_ESTest extends DeltaZigzagBinaryPacking_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[9];
      intArray0[0] = 17;
      intArray0[1] = 33554433;
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper0, (-1), intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Decoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[24];
      intArray0[0] = 4389;
      intArray0[1] = 4389;
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper0, 16, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[7];
      intArray0[0] = 262143;
      intArray0[1] = 131071;
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper0, 262143, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[14];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray1 = new int[7];
      intArray1[0] = 67108863;
      intArray1[1] = 67108863;
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress(intArray1, intWrapper0, 1, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[6];
      intArray0[0] = 331;
      intArray0[1] = (-958);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper0, 331, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[14];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray1 = new int[7];
      intArray1[0] = 67108863;
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress(intArray1, intWrapper1, 1, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 14 out of bounds for length 14
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Decoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[7];
      intArray0[1] = (-977);
      IntWrapper intWrapper0 = new IntWrapper(1);
      deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper0, (-977), intArray0, intWrapper0);
      assertEquals(2.0F, intWrapper0.floatValue(), 0.01F);
      assertEquals((short)2, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[14];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper1, 1, intArray0, intWrapper0);
      assertEquals(1.0F, intWrapper1.floatValue(), 0.01F);
      assertEquals(1, intWrapper1.get());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = new IntWrapper(4506);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.compress(intArray0, intWrapper0, 4535, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4506 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Encoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[6];
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.compress((int[]) null, intWrapper0, 3966, intArray0, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Encoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress((int[]) null, (IntWrapper) null, (-1141), (int[]) null, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.DeltaZigzagBinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(24);
      deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(24.0F, intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(24);
      deltaZigzagBinaryPacking0.compress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      assertEquals(24.0F, intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      String string0 = deltaZigzagBinaryPacking0.toString();
      assertEquals("DeltaZigzagBinaryPacking", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[9];
      intArray0[2] = 1249;
      IntWrapper intWrapper0 = new IntWrapper(1);
      deltaZigzagBinaryPacking0.compress(intArray0, intWrapper0, (-624), intArray0, intWrapper0);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress(intArray0, intWrapper0, (-2974), intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Decoder", e);
      }
  }
}
