/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:00:47 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import me.lemire.integercompression.FastPFOR;
import me.lemire.integercompression.IntWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FastPFOR_ESTest extends FastPFOR_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FastPFOR fastPFOR0 = new FastPFOR(712);
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        fastPFOR0.compress(intArray0, intWrapper0, (-1939), intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 7 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[24];
      IntWrapper intWrapper0 = new IntWrapper(0);
      intArray0[5] = 65536;
      FastPFOR fastPFOR0 = new FastPFOR(0);
      // Undeclared exception!
      try { 
        fastPFOR0.headlessUncompress(intArray0, intWrapper0, 17, intArray0, intWrapper0, (-871));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 24 out of bounds for length 24
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(256);
      // Undeclared exception!
      try { 
        fastPFOR0.headlessCompress(intArray0, intWrapper0, 256, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 257 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FastPFOR fastPFOR0 = new FastPFOR(3117);
      ByteBuffer byteBuffer0 = fastPFOR0.makeBuffer(3117);
      assertEquals(3117, byteBuffer0.remaining());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(0);
      fastPFOR0.uncompress(intArray0, intWrapper0, 2866, intArray0, intWrapper0);
      assertEquals((byte)1, intWrapper0.byteValue());
      assertEquals("1", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      int[] intArray0 = new int[33];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        fastPFOR0.headlessUncompress(intArray0, intWrapper0, 256, intArray0, intWrapper0, 325);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 65
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[4];
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = new IntWrapper(256);
      // Undeclared exception!
      try { 
        fastPFOR0.uncompress(intArray0, intWrapper0, (-806), intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 256 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      // Undeclared exception!
      try { 
        fastPFOR0.makeBuffer((-1758));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-1758 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        fastPFOR0.headlessUncompress((int[]) null, intWrapper0, 65536, (int[]) null, intWrapper0, 256);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[6];
      intArray0[0] = 2;
      intArray0[2] = 256;
      // Undeclared exception!
      try { 
        fastPFOR0.headlessUncompress(intArray0, intWrapper0, 65536, intArray0, intWrapper0, 256);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = new IntWrapper(256);
      // Undeclared exception!
      try { 
        fastPFOR0.compress((int[]) null, intWrapper0, 65536, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FastPFOR fastPFOR0 = null;
      try {
        fastPFOR0 = new FastPFOR(Integer.MIN_VALUE);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -268435456
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FastPFOR fastPFOR0 = null;
      try {
        fastPFOR0 = new FastPFOR((-1095));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-1107 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      fastPFOR0.uncompress((int[]) null, (IntWrapper) null, 0, (int[]) null, (IntWrapper) null);
      assertEquals(256, FastPFOR.BLOCK_SIZE);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = new IntWrapper(256);
      // Undeclared exception!
      try { 
        fastPFOR0.uncompress((int[]) null, intWrapper0, (-923), (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      int[] intArray0 = new int[18];
      IntWrapper intWrapper0 = new IntWrapper(0);
      fastPFOR0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0.0F, intWrapper0.floatValue(), 0.01F);
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      int[] intArray0 = new int[24];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        fastPFOR0.compress(intArray0, intWrapper0, 65536, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 24 out of bounds for length 24
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FastPFOR fastPFOR0 = new FastPFOR(3117);
      int[] intArray0 = new int[8];
      intArray0[1] = 3;
      intArray0[2] = 65536;
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        fastPFOR0.headlessUncompress(intArray0, intWrapper0, 256, intArray0, intWrapper0, (-1733));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4099 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[6];
      intArray0[1] = 65536;
      // Undeclared exception!
      try { 
        fastPFOR0.headlessUncompress(intArray0, intWrapper0, 262174, intArray0, intWrapper0, 256);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 33
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      int[] intArray0 = new int[17];
      IntWrapper intWrapper0 = new IntWrapper(0);
      fastPFOR0.headlessUncompress(intArray0, intWrapper0, 29, intArray0, intWrapper0, 29);
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(0, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = new IntWrapper(256);
      // Undeclared exception!
      try { 
        fastPFOR0.headlessCompress((int[]) null, intWrapper0, 65536, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FastPFOR fastPFOR0 = new FastPFOR(1);
      String string0 = fastPFOR0.toString();
      assertEquals("FastPFOR", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FastPFOR fastPFOR0 = FastPFOR.FastPFOR1();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[1];
      fastPFOR0.headlessCompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(256, FastPFOR.BLOCK_SIZE);
  }
}
