/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 12:57:41 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import me.lemire.integercompression.FastPFOR128;
import me.lemire.integercompression.IntWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FastPFOR128_ESTest extends FastPFOR128_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      // Undeclared exception!
      try { 
        fastPFOR128_0.compress((int[]) null, (IntWrapper) null, (-140), (int[]) null, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = new FastPFOR128(3);
      int[] intArray0 = new int[6];
      intArray0[0] = 65536;
      intArray0[2] = 3;
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        fastPFOR128_0.uncompress(intArray0, intWrapper0, 65536, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[6];
      intWrapper0.add(Integer.MAX_VALUE);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        fastPFOR128_0.headlessCompress(intArray0, intWrapper0, 128, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1 out of bounds for length 33
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      ByteBuffer byteBuffer0 = fastPFOR128_0.makeBuffer(255);
      assertEquals(255, byteBuffer0.capacity());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(4);
      fastPFOR128_0.uncompress(intArray0, intWrapper0, 128, intArray0, intWrapper0);
      assertEquals((short)5, intWrapper0.shortValue());
      assertEquals(5.0F, intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[27];
      // Undeclared exception!
      try { 
        fastPFOR128_0.uncompress(intArray0, (IntWrapper) null, (-340), intArray0, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = new FastPFOR128(3);
      int[] intArray0 = new int[6];
      intArray0[0] = 65536;
      intArray0[1] = 3;
      intArray0[4] = 65536;
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        fastPFOR128_0.uncompress(intArray0, intWrapper0, 65536, intArray0, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = new IntWrapper(1);
      int[] intArray0 = new int[8];
      intArray0[1] = 128;
      intArray0[2] = 1;
      intArray0[3] = 1;
      intArray0[4] = 128;
      // Undeclared exception!
      try { 
        fastPFOR128_0.uncompress(intArray0, intWrapper0, (-339), intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      // Undeclared exception!
      try { 
        fastPFOR128_0.makeBuffer((-1425));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-1425 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = new IntWrapper(128);
      // Undeclared exception!
      try { 
        fastPFOR128_0.headlessUncompress((int[]) null, intWrapper0, 1052, (int[]) null, intWrapper0, 1052);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[5];
      int[] intArray1 = new int[4];
      intArray1[0] = 3;
      intArray1[3] = (-1398);
      // Undeclared exception!
      try { 
        fastPFOR128_0.headlessUncompress(intArray1, intWrapper0, 1967, intArray0, intWrapper0, (-1398));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[3];
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      // Undeclared exception!
      try { 
        fastPFOR128_0.headlessCompress(intArray0, (IntWrapper) null, 0, intArray0, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        fastPFOR128_0.compress((int[]) null, intWrapper0, 128, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[133];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        fastPFOR128_0.compress(intArray0, intWrapper0, 65536, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 133 out of bounds for length 133
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = null;
      try {
        fastPFOR128_0 = new FastPFOR128(Integer.MIN_VALUE);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -268435456
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = null;
      try {
        fastPFOR128_0 = new FastPFOR128((-911));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-932 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(4030);
      int[] intArray1 = new int[5];
      fastPFOR128_0.headlessCompress(intArray0, intWrapper0, 0, intArray1, intWrapper0);
      assertEquals(65536, FastPFOR128.DEFAULT_PAGE_SIZE);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[27];
      IntWrapper intWrapper0 = new IntWrapper(0);
      fastPFOR128_0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals((short)0, intWrapper0.shortValue());
      assertEquals(0, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[5];
      fastPFOR128_0.compress(intArray0, intWrapper0, (-125), intArray0, intWrapper0);
      assertEquals(0, intWrapper0.get());
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = new FastPFOR128(3);
      int[] intArray0 = new int[6];
      intArray0[0] = 65536;
      intArray0[2] = 3;
      intArray0[3] = 3;
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        fastPFOR128_0.uncompress(intArray0, intWrapper0, 65536, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[3];
      intArray0[1] = 65536;
      intArray0[2] = 65536;
      // Undeclared exception!
      try { 
        fastPFOR128_0.headlessUncompress(intArray0, intWrapper0, 128, intArray0, intWrapper0, 65536);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 33
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[3];
      intArray0[1] = 65536;
      // Undeclared exception!
      try { 
        fastPFOR128_0.headlessUncompress(intArray0, intWrapper0, 128, intArray0, intWrapper0, 65536);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 33
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[25];
      IntWrapper intWrapper0 = new IntWrapper(0);
      fastPFOR128_0.headlessUncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, 0);
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int[] intArray0 = new int[157];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      fastPFOR128_0.headlessUncompress(intArray0, intWrapper0, 128, intArray0, intWrapper0, 128);
      assertEquals((short)128, intWrapper0.shortValue());
      assertEquals("128", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[133];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        fastPFOR128_0.headlessCompress(intArray0, intWrapper0, 128, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 133 out of bounds for length 133
         //
         verifyException("me.lemire.integercompression.FastPFOR128", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      int[] intArray0 = new int[129];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      fastPFOR128_0.compress(intArray0, intWrapper0, 128, intArray0, intWrapper1);
      assertEquals("128", intWrapper0.toString());
      assertEquals(7, intWrapper1.intValue());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      FastPFOR128 fastPFOR128_0 = FastPFOR128.FastPFOR1281();
      String string0 = fastPFOR128_0.toString();
      assertEquals("FastPFOR128", string0);
  }
}
