/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:33:29 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import me.lemire.integercompression.IntWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntWrapper_ESTest extends IntWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      intWrapper0.increment();
      long long0 = intWrapper0.longValue();
      assertEquals((short)1, intWrapper0.shortValue());
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      assertEquals(0L, intWrapper0.longValue());
      
      intWrapper0.set((-1));
      long long0 = intWrapper0.longValue();
      assertEquals((-1), intWrapper0.intValue());
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int int0 = intWrapper0.intValue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1151));
      intWrapper0.set(1919);
      int int0 = intWrapper0.intValue();
      assertEquals(1919, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int int0 = intWrapper0.get();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      intWrapper0.increment();
      int int0 = intWrapper0.get();
      assertEquals((short)1, intWrapper0.shortValue());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper(0);
      float float0 = intWrapper0.floatValue();
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      intWrapper0.increment();
      float float0 = intWrapper0.floatValue();
      assertEquals((byte)1, intWrapper0.byteValue());
      assertEquals(1.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper(542);
      double double0 = intWrapper0.doubleValue();
      assertEquals(542.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1151));
      double double0 = intWrapper0.doubleValue();
      assertEquals((-1151.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1151));
      int int0 = intWrapper0.intValue();
      assertEquals((-1151), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1151));
      float float0 = intWrapper0.floatValue();
      assertEquals((-1151.0F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1151));
      String string0 = intWrapper0.toString();
      assertEquals("-1151", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1151));
      intWrapper0.add((-80));
      assertEquals((-1231L), intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1151));
      int int0 = intWrapper0.get();
      assertEquals((-1151), int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      double double0 = intWrapper0.doubleValue();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      long long0 = intWrapper0.longValue();
      assertEquals(0L, long0);
  }
}
