/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 12:54:28 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.JustCopy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JustCopy_ESTest extends JustCopy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      int[] intArray0 = new int[9];
      IntWrapper intWrapper0 = new IntWrapper(562);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        justCopy0.compress(intArray0, intWrapper1, 0, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      int[] intArray0 = new int[4];
      int[] intArray1 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper((-1004));
      // Undeclared exception!
      try { 
        justCopy0.compress(intArray1, intWrapper0, 0, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = new IntWrapper(0);
      justCopy0.headlessUncompress(intArray0, intWrapper0, 3738, intArray0, intWrapper0, 0);
      assertEquals((byte)0, intWrapper0.byteValue());
      assertEquals("0", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[5];
      IntWrapper intWrapper1 = new IntWrapper(0);
      justCopy0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper1);
      assertEquals((byte)0, intWrapper1.byteValue());
      assertEquals(0.0, intWrapper1.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[5];
      int[] intArray1 = new int[6];
      justCopy0.uncompress(intArray0, intWrapper0, 0, intArray1, intWrapper0);
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[5];
      IntWrapper intWrapper1 = new IntWrapper(0);
      justCopy0.headlessCompress(intArray1, intWrapper1, 0, intArray0, intWrapper0);
      assertEquals(0L, intWrapper0.longValue());
      assertEquals((short)0, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      // Undeclared exception!
      try { 
        justCopy0.uncompress((int[]) null, (IntWrapper) null, 928, (int[]) null, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.JustCopy", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = new IntWrapper(0);
      intWrapper0.set(1921);
      // Undeclared exception!
      try { 
        justCopy0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      IntWrapper intWrapper0 = new IntWrapper((-56));
      // Undeclared exception!
      try { 
        justCopy0.headlessUncompress((int[]) null, intWrapper0, (-56), (int[]) null, intWrapper0, (-56));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[5];
      // Undeclared exception!
      try { 
        justCopy0.headlessUncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      // Undeclared exception!
      try { 
        justCopy0.headlessCompress((int[]) null, (IntWrapper) null, 0, (int[]) null, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.JustCopy", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        justCopy0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        justCopy0.compress((int[]) null, intWrapper0, 1, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(0);
      justCopy0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0L, intWrapper0.longValue());
      assertEquals(0, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JustCopy justCopy0 = new JustCopy();
      String string0 = justCopy0.toString();
      assertEquals("JustCopy", string0);
  }
}
