/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 12:58:53 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.Kamikaze;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Kamikaze_ESTest extends Kamikaze_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(2);
      IntWrapper intWrapper1 = new IntWrapper(31);
      kamikaze0.uncompress(intArray0, intWrapper0, 3751, intArray0, intWrapper1);
      assertEquals("3", intWrapper0.toString());
      assertEquals((short)3, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(2);
      int[] intArray1 = new int[1];
      kamikaze0.uncompress(intArray0, intWrapper0, 3751, intArray1, intWrapper0);
      assertEquals((byte)3, intWrapper0.byteValue());
      assertEquals((short)3, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[1];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        kamikaze0.compress(intArray0, intWrapper0, 1731, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("com.kamikaze.pfordelta.PForDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[3];
      kamikaze0.compress(intArray0, intWrapper0, (-2204), intArray1, intWrapper0);
      assertEquals(1L, intWrapper0.longValue());
      assertArrayEquals(new int[] {0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      kamikaze0.headlessUncompress(intArray0, intWrapper0, 415, intArray0, intWrapper1, 1645);
      assertEquals((byte)2, intWrapper0.byteValue());
      assertEquals(1536L, intWrapper1.longValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper(0);
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[2];
      int[] intArray1 = new int[3];
      kamikaze0.headlessUncompress(intArray0, intWrapper0, (-5059), intArray1, intWrapper0, 134217727);
      assertEquals((byte) (-126), intWrapper0.byteValue());
      assertEquals((short) (-126), intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(2);
      kamikaze0.headlessUncompress(intArray0, intWrapper0, 3465, intArray0, intWrapper0, (-4772));
      assertEquals(2L, intWrapper0.longValue());
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[5];
      int[] intArray1 = new int[8];
      // Undeclared exception!
      try { 
        kamikaze0.headlessCompress(intArray0, (IntWrapper) null, 1934, intArray1, (IntWrapper) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("com.kamikaze.pfordelta.PForDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(1082);
      // Undeclared exception!
      try { 
        kamikaze0.uncompress(intArray0, intWrapper0, 1082, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1082 out of bounds for length 0
         //
         verifyException("me.lemire.integercompression.Kamikaze", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      // Undeclared exception!
      try { 
        kamikaze0.headlessUncompress((int[]) null, (IntWrapper) null, 927, (int[]) null, (IntWrapper) null, 927);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.kamikaze.pfordelta.PForDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      IntWrapper intWrapper0 = new IntWrapper(Integer.MAX_VALUE);
      // Undeclared exception!
      try { 
        kamikaze0.headlessUncompress((int[]) null, intWrapper0, Integer.MAX_VALUE, (int[]) null, intWrapper0, Integer.MAX_VALUE);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -256
         //
         verifyException("com.kamikaze.pfordelta.PForDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        kamikaze0.headlessUncompress(intArray0, (IntWrapper) null, 1647, intArray0, (IntWrapper) null, 1647);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("com.kamikaze.pfordelta.PForDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(0);
      kamikaze0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      // Undeclared exception!
      try { 
        kamikaze0.uncompress((int[]) null, (IntWrapper) null, (-1024), (int[]) null, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Kamikaze", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      kamikaze0.compress((int[]) null, (IntWrapper) null, 11, (int[]) null, (IntWrapper) null);
      assertEquals("Kamikaze's PForDelta", kamikaze0.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      // Undeclared exception!
      try { 
        kamikaze0.compress((int[]) null, (IntWrapper) null, 1048448, (int[]) null, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Kamikaze", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      // Undeclared exception!
      try { 
        kamikaze0.headlessCompress((int[]) null, (IntWrapper) null, 861, (int[]) null, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.kamikaze.pfordelta.PForDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      int[] intArray0 = new int[4];
      kamikaze0.headlessCompress(intArray0, (IntWrapper) null, 0, intArray0, (IntWrapper) null);
      assertArrayEquals(new int[] {0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Kamikaze kamikaze0 = new Kamikaze();
      String string0 = kamikaze0.toString();
      assertEquals("Kamikaze's PForDelta", string0);
  }
}
