/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:06:57 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.NewPFD;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NewPFD_ESTest extends NewPFD_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[3];
      intArray0[0] = 5465;
      intArray0[1] = (-3436);
      // Undeclared exception!
      try { 
        newPFD0.uncompress(intArray0, intWrapper0, (-1841), intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 3
         //
         verifyException("me.lemire.integercompression.S16", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[33];
      NewPFD newPFD0 = new NewPFD();
      int[] intArray1 = new int[3];
      intArray1[0] = 3842;
      // Undeclared exception!
      try { 
        newPFD0.headlessUncompress(intArray1, intWrapper0, 15, intArray0, intWrapper0, 2147483520);
       //  fail("Expecting exception: ArrayIndexOutOfBoundsException");
       // Unstable assertion
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 64
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(5);
      newPFD0.headlessUncompress(intArray0, intWrapper0, 2783, intArray0, intWrapper0, (-711));
      assertEquals(8, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      // Undeclared exception!
      try { 
        newPFD0.headlessUncompress((int[]) null, (IntWrapper) null, (-477), (int[]) null, (IntWrapper) null, (-477));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.NewPFD", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        newPFD0.headlessCompress(intArray0, intWrapper0, 219, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[4];
      NewPFD.getBestBFromData(intArray0, Integer.MAX_VALUE, intWrapper0, intWrapper0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[1];
      IntWrapper intWrapper0 = new IntWrapper((-1991));
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      newPFD0.compress(intArray0, intWrapper0, (-1991), intArray0, intWrapper1);
      assertEquals((byte)1, intWrapper1.byteValue());
      assertEquals((byte)57, intWrapper0.byteValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        newPFD0.uncompress((int[]) null, intWrapper0, 2209, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.NewPFD", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[6];
      NewPFD newPFD0 = new NewPFD();
      IntWrapper intWrapper1 = new IntWrapper(2147483638);
      // Undeclared exception!
      try { 
        newPFD0.headlessUncompress(intArray0, intWrapper0, 2147483638, intArray0, intWrapper1, 2147483638);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // fromIndex(2147483638) > toIndex(-2147483626)
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      IntWrapper intWrapper0 = new IntWrapper(2884);
      // Undeclared exception!
      try { 
        newPFD0.headlessCompress((int[]) null, intWrapper0, 2884, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntWrapper intWrapper0 = new IntWrapper((-1231));
      // Undeclared exception!
      try { 
        NewPFD.getBestBFromData((int[]) null, (-1231), intWrapper0, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[1];
      IntWrapper intWrapper0 = new IntWrapper(536870911);
      // Undeclared exception!
      try { 
        NewPFD.getBestBFromData(intArray0, 536870911, intWrapper0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 536870911 out of bounds for length 1
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        newPFD0.compress((int[]) null, intWrapper0, 2884, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.NewPFD", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      newPFD0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals("0", intWrapper0.toString());
      assertEquals(0, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[6];
      newPFD0.uncompress(intArray0, intWrapper0, 2209, intArray0, intWrapper0);
      assertEquals((short)1, intWrapper0.shortValue());
      assertEquals(1, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      newPFD0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
      assertEquals((short)0, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[2];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        newPFD0.compress(intArray0, intWrapper0, 5376, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[5];
      IntWrapper intWrapper0 = new IntWrapper(0);
      newPFD0.headlessUncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, 0);
      assertEquals(0, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      IntWrapper intWrapper0 = new IntWrapper((-1071));
      newPFD0.headlessCompress((int[]) null, intWrapper0, (-1071), (int[]) null, intWrapper0);
      assertEquals((short) (-1071), intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper1 = new IntWrapper(2147483622);
      NewPFD newPFD0 = new NewPFD();
      // Undeclared exception!
      try { 
        newPFD0.headlessCompress(intArray0, intWrapper1, 2147483622, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -2147483546 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper(544);
      newPFD0.headlessCompress(intArray0, intWrapper0, 0, (int[]) null, intWrapper0);
      assertEquals(544.0F, intWrapper0.floatValue(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      NewPFD newPFD0 = new NewPFD();
      String string0 = newPFD0.toString();
      assertEquals("NewPFD", string0);
  }
}
