/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:05:48 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.OptPFDS16;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OptPFDS16_ESTest extends OptPFDS16_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      IntWrapper intWrapper0 = new IntWrapper((-4068));
      // Undeclared exception!
      try { 
        optPFDS16_0.uncompress((int[]) null, intWrapper0, (-4068), (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.OptPFDS16", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray0 = new int[9];
      intArray0[0] = 524287;
      // Undeclared exception!
      try { 
        optPFDS16_0.headlessUncompress(intArray0, intWrapper0, 524287, intArray0, intWrapper0, 865);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 255 out of bounds for length 17
         //
         verifyException("me.lemire.integercompression.OptPFDS16", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray0 = new int[8];
      intArray0[0] = 1914;
      intArray0[1] = (-686);
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        optPFDS16_0.uncompress(intArray0, intWrapper0, 13, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[88];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray1 = new int[4];
      intArray1[0] = 1281;
      // Undeclared exception!
      try { 
        optPFDS16_0.headlessUncompress(intArray1, intWrapper0, 67108863, intArray0, intWrapper0, 3529);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 88 out of bounds for length 88
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray0 = new int[1];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      optPFDS16_0.headlessUncompress(intArray0, intWrapper0, (-1268), intArray0, intWrapper0, (-1268));
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[135];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      IntWrapper intWrapper1 = new IntWrapper(15);
      // Undeclared exception!
      try { 
        optPFDS16_0.compress(intArray0, intWrapper0, 2169, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 135 out of bounds for length 135
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray0 = new int[3];
      IntWrapper intWrapper0 = new IntWrapper(Integer.MAX_VALUE);
      // Undeclared exception!
      try { 
        optPFDS16_0.headlessCompress(intArray0, intWrapper0, (-307), intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2147483647 out of bounds for length 3
         //
         verifyException("me.lemire.integercompression.OptPFDS16", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        optPFDS16_0.headlessUncompress((int[]) null, intWrapper0, 881, (int[]) null, intWrapper0, 881);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.OptPFDS16", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      IntWrapper intWrapper0 = new IntWrapper(135);
      // Undeclared exception!
      try { 
        optPFDS16_0.headlessCompress((int[]) null, intWrapper0, 135, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      IntWrapper intWrapper0 = new IntWrapper((-560));
      // Undeclared exception!
      try { 
        optPFDS16_0.compress((int[]) null, intWrapper0, (-560), (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.OptPFDS16", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(0);
      optPFDS16_0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals((short)0, intWrapper0.shortValue());
      assertEquals(0, intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray0 = new int[6];
      IntWrapper intWrapper0 = new IntWrapper(0);
      optPFDS16_0.uncompress(intArray0, intWrapper0, 6, intArray0, intWrapper0);
      assertEquals((short)1, intWrapper0.shortValue());
      assertEquals(1.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(0);
      optPFDS16_0.compress(intArray0, intWrapper0, 22, intArray0, intWrapper0);
      assertEquals((byte)0, intWrapper0.byteValue());
      assertEquals("0", intWrapper0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[4];
      optPFDS16_0.headlessUncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, 0);
      assertEquals(0, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int[] intArray0 = new int[135];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      // Undeclared exception!
      try { 
        optPFDS16_0.headlessUncompress(intArray0, intWrapper0, 8191, intArray0, intWrapper0, 8191);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 160
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int[] intArray0 = new int[135];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      optPFDS16_0.compress(intArray0, intWrapper0, (-562), intArray0, intWrapper0);
      // Undeclared exception!
      try { 
        optPFDS16_0.headlessCompress(intArray0, intWrapper1, 2144, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 135 out of bounds for length 135
         //
         verifyException("me.lemire.integercompression.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[5];
      optPFDS16_0.headlessCompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int[] intArray0 = new int[135];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      optPFDS16_0.compress(intArray0, intWrapper0, (-562), intArray0, intWrapper0);
      assertEquals((byte)1, intWrapper0.byteValue());
      assertEquals(1, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      OptPFDS16 optPFDS16_0 = new OptPFDS16();
      String string0 = optPFDS16_0.toString();
      assertEquals("OptPFDS16", string0);
  }
}
