/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 12:52:09 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.S9;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class S9_ESTest extends S9_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int[] intArray0 = new int[4];
      intArray0[1] = 268435456;
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 1, 29, intArray0, 1, 30);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[6];
      intArray0[1] = 268435467;
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 1, Integer.MIN_VALUE, intArray0, Integer.MIN_VALUE, Integer.MIN_VALUE);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 7;
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 0, 0, intArray0, 3, 562);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 1
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int[] intArray0 = new int[8];
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 2, 7, intArray0, (-2787), Integer.MIN_VALUE);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int[] intArray0 = new int[7];
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 0, (-860), intArray0, 2771, 28);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2771 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[8];
      S9.uncompress(intArray0, 5, 4, intArray0, 3754, (-587));
      assertEquals(8, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[3] = 2242;
      S9.compress(intArray0, 1, 5, intArray0, 0);
      // Undeclared exception!
      try { 
        S9.estimatecompress(intArray0, 0, 555);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Too big a number
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[0] = (-3454);
      int int0 = S9.estimatecompress(intArray0, 0, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[14];
      int int0 = S9.estimatecompress(intArray0, 1, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int[] intArray0 = new int[8];
      int int0 = S9.compress(intArray0, (-320), (-1866), intArray0, 18);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        S9.uncompress((int[]) null, 5, 5, (int[]) null, 5, 5);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        S9.estimatecompress((int[]) null, 1, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        S9.compress((int[]) null, 26, 26, (int[]) null, 26);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int[] intArray0 = new int[7];
      int int0 = S9.estimatecompress(intArray0, 31, (-2667));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[1] = (-2787);
      intArray0[4] = (-2787);
      S9.compress(intArray0, 1, 5, intArray0, 0);
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 1, 5, intArray0, 12, 4);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 12 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int[] intArray0 = new int[14];
      intArray0[5] = 33;
      S9.compress(intArray0, 2, 8, intArray0, 2);
      S9.uncompress(intArray0, 2, 3453, intArray0, 2, 2);
      assertEquals(14, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      int[] intArray0 = new int[12];
      intArray0[6] = 8;
      S9.compress(intArray0, 2, 8, intArray0, 2);
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 2, 0, intArray0, 8, 8);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 12 out of bounds for length 12
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[5] = (-2798);
      intArray0[6] = 5;
      S9.compress(intArray0, 2, 5, intArray0, 0);
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 2, 60, intArray0, (-1903), 3208);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1903 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int[] intArray0 = new int[40];
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 5, 0, intArray0, 1, 2914);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 40 out of bounds for length 40
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[1] = (-2787);
      intArray0[3] = (-2787);
      S9.compress(intArray0, 1, 5, intArray0, 0);
      S9.uncompress(intArray0, 1, 0, intArray0, 1, 1);
      assertArrayEquals(new int[] {(-2787), 0, (-2787), 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      int[] intArray0 = new int[10];
      intArray0[5] = 1984;
      S9.compress(intArray0, 2, 4, intArray0, 2);
      S9.uncompress(intArray0, 2, 0, intArray0, 0, 4);
      assertArrayEquals(new int[] {0, 0, 0, 1984, 0, 1984, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      int[] intArray0 = new int[14];
      intArray0[5] = 33;
      S9.compress(intArray0, 2, 8, intArray0, 2);
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 2, 33, intArray0, 8, 8);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 14 out of bounds for length 14
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      int[] intArray0 = new int[14];
      intArray0[5] = 17;
      S9.compress(intArray0, 2, 8, intArray0, 2);
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 2, 17, intArray0, 8, 8);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 14 out of bounds for length 14
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int[] intArray0 = new int[12];
      intArray0[6] = 8;
      S9.compress(intArray0, 2, 8, intArray0, 2);
      S9.uncompress(intArray0, 2, 585, intArray0, 8, 2);
      assertEquals(12, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[5] = (-2798);
      intArray0[6] = 5;
      S9.compress(intArray0, 2, 5, intArray0, 0);
      S9.uncompress(intArray0, 2, 2, intArray0, 0, 2);
      assertArrayEquals(new int[] {5, 0, 620756992, 0, 0, (-2798), 5, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      int[] intArray0 = new int[2];
      intArray0[1] = 268435471;
      S9.uncompress(intArray0, 1, 1, intArray0, 1, 1);
      assertArrayEquals(new int[] {0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[1] = (-2787);
      // Undeclared exception!
      try { 
        S9.uncompress(intArray0, 1, 0, intArray0, 1, 1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // shouldn't happen
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      int[] intArray0 = new int[4];
      intArray0[1] = 268435456;
      // Undeclared exception!
      try { 
        S9.compress(intArray0, 1, 1, intArray0, 1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Too big a number
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int[] intArray0 = new int[14];
      intArray0[5] = (-2761);
      S9.compress(intArray0, 2, 5, intArray0, 2);
      S9.uncompress(intArray0, 2, 2, intArray0, 0, 2);
      assertEquals(14, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      int[] intArray0 = new int[8];
      // Undeclared exception!
      try { 
        S9.compress(intArray0, 134217728, 1, intArray0, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 134217728 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int[] intArray0 = new int[13];
      intArray0[0] = 268435413;
      // Undeclared exception!
      try { 
        S9.estimatecompress(intArray0, 0, 268435413);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 13 out of bounds for length 13
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int[] intArray0 = new int[5];
      intArray0[2] = 268435456;
      // Undeclared exception!
      try { 
        S9.estimatecompress(intArray0, 2, 32);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Too big a number
         //
         verifyException("me.lemire.integercompression.S9", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      S9 s9_0 = new S9();
  }
}
