/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:20:32 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.Simple16;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Simple16_ESTest extends Simple16_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[9];
      simple16_0.uncompress(intArray1, intWrapper0, (-1421), intArray0, intWrapper0);
      assertEquals((short)1, intWrapper0.shortValue());
      assertEquals(1.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      simple16_0.uncompress(intArray0, intWrapper0, (-1421), intArray0, intWrapper1);
      assertEquals(1.0, intWrapper0.doubleValue(), 0.01);
      assertEquals(0.0, intWrapper1.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[3];
      // Undeclared exception!
      try { 
        simple16_0.uncompress((int[]) null, intWrapper0, 1202, intArray0, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[9];
      simple16_0.compress(intArray0, intWrapper0, (-2027), intArray1, intWrapper0);
      assertEquals((short)1, intWrapper0.shortValue());
      assertArrayEquals(new int[] {(-2027), 0, 0, 0, 0, 0, 0, 0, 0}, intArray1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper((-1));
      int[] intArray1 = new int[9];
      // Undeclared exception!
      try { 
        simple16_0.compress(intArray0, intWrapper0, 1708, intArray1, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1 out of bounds for length 9
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int[] intArray0 = new int[21];
      Simple16.uncompress(intArray0, 6, 6, intArray0, 6, 6);
      assertEquals(21, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[32];
      Simple16.uncompress(intArray0, (-2298), (-2298), intArray0, (-2298), 16390);
      assertEquals(32, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[2];
      // Undeclared exception!
      try { 
        Simple16.uncompress(intArray0, 6, 1, intArray0, 13, 7324);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int[] intArray0 = new int[2];
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray1 = new int[5];
      simple16_0.headlessUncompress(intArray1, intWrapper0, 268435456, intArray0, intWrapper0, 1);
      assertEquals((byte)1, intWrapper0.byteValue());
      assertEquals((short)1, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int[] intArray0 = new int[21];
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntWrapper intWrapper1 = new IntWrapper(1);
      simple16_0.headlessUncompress(intArray0, intWrapper1, 12, intArray0, intWrapper0, 12);
      assertEquals(2.0, intWrapper1.doubleValue(), 0.01);
      assertEquals(12L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[7];
      intArray0[4] = 1887436800;
      IntWrapper intWrapper0 = new IntWrapper(4);
      // Undeclared exception!
      try { 
        simple16_0.headlessUncompress(intArray0, intWrapper0, 2051, intArray0, intWrapper0, 6);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 7 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int[] intArray0 = new int[21];
      // Undeclared exception!
      try { 
        Simple16.uncompress(intArray0, 1, 1, intArray0, (-1), 28);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1 out of bounds for length 21
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[7];
      intArray0[1] = 2039;
      intArray0[2] = (-913);
      IntWrapper intWrapper0 = new IntWrapper(0);
      intWrapper0.increment();
      // Undeclared exception!
      try { 
        simple16_0.uncompress(intArray0, intWrapper0, 2, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 7 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int[] intArray0 = new int[29];
      intArray0[0] = 8;
      int int0 = Simple16.decompressblock(intArray0, 8, intArray0, 0, 8);
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[5];
      intArray0[2] = 23;
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        simple16_0.compress(intArray0, intWrapper0, 715, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int[] intArray0 = new int[29];
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = new IntWrapper(8);
      IntWrapper intWrapper1 = new IntWrapper(8);
      simple16_0.compress(intArray0, intWrapper0, 8, intArray0, intWrapper1);
      assertEquals(11L, intWrapper1.longValue());
      assertEquals(16, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      int[] intArray0 = new int[21];
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      IntWrapper intWrapper1 = new IntWrapper(12);
      // Undeclared exception!
      try { 
        simple16_0.compress(intArray0, intWrapper0, 1931, intArray0, intWrapper1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Too big a number
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[9];
      // Undeclared exception!
      try { 
        simple16_0.headlessCompress(intArray0, intWrapper0, 27, intArray1, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 7 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int[] intArray0 = new int[40];
      int int0 = Simple16.decompressblock(intArray0, 8, intArray0, 0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      int[] intArray0 = new int[5];
      int int0 = Simple16.decompressblock(intArray0, 305, intArray0, 4, (-127));
      assertEquals((-127), int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      int[] intArray0 = new int[2];
      int int0 = Simple16.compressblock(intArray0, 0, intArray0, 0, 0);
      assertArrayEquals(new int[] {0, 0}, intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      int[] intArray0 = new int[10];
      // Undeclared exception!
      try { 
        Simple16.uncompress(intArray0, 6, 6, (int[]) null, 6, 6);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      int[] intArray0 = new int[1];
      Simple16 simple16_0 = new Simple16();
      // Undeclared exception!
      try { 
        simple16_0.headlessUncompress(intArray0, (IntWrapper) null, 15, intArray0, (IntWrapper) null, 15);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      int[] intArray0 = new int[21];
      Simple16 simple16_0 = new Simple16();
      // Undeclared exception!
      try { 
        simple16_0.headlessCompress(intArray0, (IntWrapper) null, 12, intArray0, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      // Undeclared exception!
      try { 
        Simple16.decompressblock((int[]) null, (-2747), (int[]) null, (-2747), (-2747));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        Simple16.compressblock((int[]) null, 273, (int[]) null, 273, 273);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = new IntWrapper(2);
      // Undeclared exception!
      try { 
        simple16_0.compress((int[]) null, intWrapper0, 2, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      int[] intArray0 = new int[16];
      // Undeclared exception!
      try { 
        Simple16.decompressblock(intArray0, 32, intArray0, 0, 32);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 32 out of bounds for length 16
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      int[] intArray0 = new int[21];
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      simple16_0.compress(intArray0, intWrapper0, 12, intArray0, intWrapper0);
      assertEquals(2, intWrapper0.intValue());
      
      int int0 = Simple16.compressblock(intArray0, 12, intArray0, 0, 4722);
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      int[] intArray0 = new int[10];
      // Undeclared exception!
      try { 
        Simple16.compressblock(intArray0, 0, intArray0, 0, 32);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 10 out of bounds for length 10
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int[] intArray0 = new int[21];
      int int0 = Simple16.compressblock(intArray0, 0, intArray0, 0, (-13));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int[] intArray0 = new int[21];
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      simple16_0.compress(intArray0, intWrapper0, 12, intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(12);
      intWrapper1.increment();
      simple16_0.compress(intArray0, intWrapper0, 12, intArray0, intWrapper1);
      // Undeclared exception!
      try { 
        simple16_0.headlessCompress(intArray0, intWrapper0, 12, intArray0, intWrapper1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Too big a number
         //
         verifyException("me.lemire.integercompression.Simple16", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      int[] intArray0 = new int[34];
      IntWrapper intWrapper0 = new IntWrapper(2);
      Simple16 simple16_0 = new Simple16();
      simple16_0.headlessCompress(intArray0, intWrapper0, 31, intArray0, intWrapper0);
      assertEquals(4L, intWrapper0.longValue());
      assertEquals(4.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      int[] intArray0 = new int[2];
      Simple16 simple16_0 = new Simple16();
      simple16_0.uncompress(intArray0, (IntWrapper) null, 0, intArray0, (IntWrapper) null);
      assertEquals(2, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      int[] intArray0 = new int[34];
      IntWrapper intWrapper0 = new IntWrapper(2);
      Simple16 simple16_0 = new Simple16();
      simple16_0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals((byte)2, intWrapper0.byteValue());
      assertEquals(2L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      IntWrapper intWrapper0 = new IntWrapper((-1485));
      simple16_0.headlessUncompress((int[]) null, intWrapper0, (-1485), (int[]) null, intWrapper0, (-1485));
      assertEquals((-1485.0F), intWrapper0.floatValue(), 0.01F);
      assertEquals((-1485.0), intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      int[] intArray0 = new int[32];
      Simple16.uncompress(intArray0, 1, 1, intArray0, 1, 38);
      assertEquals(32, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Simple16 simple16_0 = new Simple16();
      String string0 = simple16_0.toString();
      assertEquals("Simple16", string0);
  }
}
