/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:28:49 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.VariableByte;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VariableByte_ESTest extends VariableByte_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[8];
      intArray0[1] = (-1757);
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        variableByte0.headlessUncompress(intArray0, intWrapper0, 127, intArray0, intWrapper0, 2304);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper((-246));
      variableByte0.headlessUncompress(intArray0, intWrapper0, (-2629), intArray0, intWrapper0, (-1));
      assertEquals((-246L), intWrapper0.longValue());
      assertEquals((short) (-246), intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[9];
      byte[] byteArray0 = new byte[6];
      byteArray0[1] = (byte) (-1);
      byteArray0[4] = (byte)50;
      // Undeclared exception!
      try { 
        variableByte0.uncompress(byteArray0, intWrapper0, (int) (byte)50, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[3];
      byte[] byteArray0 = new byte[4];
      byteArray0[1] = (byte)2;
      // Undeclared exception!
      try { 
        variableByte0.uncompress(byteArray0, intWrapper0, (int) (byte)2, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 4 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[4];
      byte[] byteArray0 = new byte[2];
      byteArray0[0] = (byte)89;
      // Undeclared exception!
      try { 
        variableByte0.uncompress(byteArray0, intWrapper0, (int) (byte)89, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      byte[] byteArray0 = new byte[5];
      IntWrapper intWrapper0 = new IntWrapper(1705);
      int[] intArray0 = new int[0];
      variableByte0.uncompress(byteArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(3410, intWrapper0.get());
      assertEquals((short)3410, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[9];
      intArray0[0] = 1247;
      intArray0[1] = 1247;
      intArray0[3] = 1247;
      intArray0[4] = 242;
      intArray0[5] = 1247;
      intArray0[8] = 1247;
      // Undeclared exception!
      try { 
        variableByte0.uncompress(intArray0, intWrapper0, 877, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(1341);
      variableByte0.uncompress(intArray0, intWrapper0, (-1405), intArray0, intWrapper0);
      assertEquals((-64L), intWrapper0.longValue());
      assertEquals((-64), intWrapper0.get());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[8];
      intArray0[1] = 128;
      byte[] byteArray0 = new byte[8];
      // Undeclared exception!
      try { 
        variableByte0.compress(intArray0, intWrapper0, 128, byteArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray0 = new int[6];
      byte[] byteArray0 = new byte[5];
      variableByte0.compress(intArray0, intWrapper0, 1, byteArray0, intWrapper0);
      assertEquals("2", intWrapper0.toString());
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      int[] intArray0 = new int[8];
      intArray0[1] = 128;
      // Undeclared exception!
      try { 
        variableByte0.headlessCompress(intArray0, intWrapper0, 2347, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      ByteBuffer byteBuffer0 = variableByte0.makeBuffer(773);
      assertEquals(773, byteBuffer0.limit());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[3];
      byte[] byteArray0 = new byte[9];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        variableByte0.uncompress(byteArray0, intWrapper0, (int) (byte)74, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(1341);
      variableByte0.compress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(4, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[8];
      intArray0[1] = (-1757);
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      byte[] byteArray0 = new byte[8];
      // Undeclared exception!
      try { 
        variableByte0.compress(intArray0, intWrapper0, 2171, byteArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      IntWrapper intWrapper0 = new IntWrapper(1023);
      // Undeclared exception!
      try { 
        variableByte0.uncompress((int[]) null, intWrapper0, 1023, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[5];
      byte[] byteArray0 = new byte[0];
      // Undeclared exception!
      try { 
        variableByte0.uncompress(byteArray0, (IntWrapper) null, 15, intArray0, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      // Undeclared exception!
      try { 
        variableByte0.makeBuffer((-791));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-791 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[4];
      // Undeclared exception!
      try { 
        variableByte0.headlessUncompress(intArray0, (IntWrapper) null, 1009, intArray0, (IntWrapper) null, 1009);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[8];
      // Undeclared exception!
      try { 
        variableByte0.headlessCompress(intArray0, (IntWrapper) null, 21, intArray0, (IntWrapper) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[12];
      IntWrapper intWrapper0 = new IntWrapper((-25));
      // Undeclared exception!
      try { 
        variableByte0.headlessCompress(intArray0, intWrapper0, (-2130836486), intArray0, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[7];
      // Undeclared exception!
      try { 
        variableByte0.headlessCompress(intArray0, intWrapper0, (-829), intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-6632 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      // Undeclared exception!
      try { 
        variableByte0.compress((int[]) null, intWrapper0, 4957, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = new IntWrapper(2147423175);
      // Undeclared exception!
      try { 
        variableByte0.compress(intArray0, intWrapper0, (-2147339733), intArray0, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int[] intArray0 = new int[10];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      // Undeclared exception!
      try { 
        variableByte0.compress(intArray0, intWrapper0, (-3474), intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-27792 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      // Undeclared exception!
      try { 
        variableByte0.compress((int[]) null, intWrapper0, 788, (byte[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[5];
      variableByte0.headlessUncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0, 0);
      assertEquals(0.0F, intWrapper0.floatValue(), 0.01F);
      assertEquals((short)0, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[3];
      intArray0[1] = 1278;
      variableByte0.headlessUncompress(intArray0, intWrapper0, 1278, intArray0, intWrapper0, 1);
      assertEquals(2.0, intWrapper0.doubleValue(), 0.01);
      assertArrayEquals(new int[] {(-536870912), 1278, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[9];
      byte[] byteArray0 = new byte[6];
      byteArray0[1] = (byte) (-1);
      byteArray0[5] = (byte) (-103);
      // Undeclared exception!
      try { 
        variableByte0.uncompress(byteArray0, intWrapper0, (int) (byte)50, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 6 out of bounds for length 6
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      byte[] byteArray0 = new byte[2];
      byteArray0[0] = (byte) (-128);
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        variableByte0.uncompress(byteArray0, intWrapper0, 23, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[3];
      byte[] byteArray0 = new byte[4];
      byteArray0[2] = (byte) (-62);
      variableByte0.uncompress(byteArray0, intWrapper0, (int) (byte)2, intArray0, intWrapper0);
      assertEquals((byte)4, intWrapper0.byteValue());
      assertArrayEquals(new int[] {1081344, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[7];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      variableByte0.uncompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0.0F, intWrapper0.floatValue(), 0.01F);
      assertEquals((short)0, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[3];
      intArray0[0] = 1463;
      variableByte0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      byte[] byteArray0 = new byte[5];
      // Undeclared exception!
      try { 
        variableByte0.compress(intArray0, intWrapper1, 1905, byteArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 3
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[8];
      IntWrapper intWrapper0 = new IntWrapper((-84));
      byte[] byteArray0 = new byte[0];
      variableByte0.compress(intArray0, intWrapper0, (-84), byteArray0, intWrapper0);
      assertEquals((byte)88, intWrapper0.byteValue());
      assertEquals((-168.0), intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[5];
      variableByte0.compress(intArray0, intWrapper0, 0, (byte[]) null, intWrapper0);
      assertEquals(0.0F, intWrapper0.floatValue(), 0.01F);
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[8];
      intArray0[1] = (-1757);
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        variableByte0.headlessCompress(intArray0, intWrapper0, 193, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[19];
      variableByte0.headlessCompress(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0L, intWrapper0.longValue());
      assertEquals(0, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      VariableByte variableByte0 = new VariableByte();
      String string0 = variableByte0.toString();
      assertEquals("VariableByte", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[1];
      // Undeclared exception!
      try { 
        variableByte0.compress(intArray0, intWrapper0, 4986, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      VariableByte variableByte0 = new VariableByte();
      int[] intArray0 = new int[3];
      intArray0[0] = 1463;
      variableByte0.headlessCompress(intArray0, intWrapper0, 1, intArray0, intWrapper0);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      variableByte0.headlessCompress(intArray0, intWrapper1, 1, intArray0, intWrapper0);
      byte[] byteArray0 = new byte[5];
      // Undeclared exception!
      try { 
        variableByte0.compress(intArray0, intWrapper1, 1905, byteArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("me.lemire.integercompression.VariableByte", e);
      }
  }
}
