/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:02:24 GMT 2024
 */

package dk.tbsalling.aismessages.nmea;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import java.io.InputStream;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NMEAMessageInputStreamReader_ESTest extends NMEAMessageInputStreamReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      NMEAMessageInputStreamReader nMEAMessageInputStreamReader0 = new NMEAMessageInputStreamReader((InputStream) null, consumer0);
      assertFalse(nMEAMessageInputStreamReader0.isStopRequested());
      
      nMEAMessageInputStreamReader0.requestStop();
      Boolean boolean0 = nMEAMessageInputStreamReader0.isStopRequested();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      NMEAMessageInputStreamReader nMEAMessageInputStreamReader0 = new NMEAMessageInputStreamReader((InputStream) null, consumer0);
      Boolean boolean0 = nMEAMessageInputStreamReader0.isStopRequested();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NMEAMessageInputStreamReader nMEAMessageInputStreamReader0 = new NMEAMessageInputStreamReader((InputStream) null, (Consumer<? super NMEAMessage>) null);
      // Undeclared exception!
      try { 
        nMEAMessageInputStreamReader0.run();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class java.util.logging.LogRecord$CallerFinder
         //
         verifyException("java.util.logging.LogRecord", e);
      }
  }
}
