from __future__ import annotations
import time
import re
import os
import datetime
from abc import ABC
import pathlib
from io import StringIO
import io
from io import BytesIO
import typing
from typing import *
from src.main.org.apache.commons.graph.Graph import *
from src.main.org.apache.commons.graph.Mapper import *
from src.main.org.apache.commons.graph.VertexPair import *
from src.main.org.apache.commons.graph.export.GraphExportException import *
from src.main.org.apache.commons.graph.utils.Assertions import *


class AbstractExporter(ABC):

    __writer: typing.Union[io.TextIOWrapper, io.BufferedWriter] = None

    __name: str = ""

    __edgeProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None

    __vertexProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None

    __graph: Graph[typing.Any, typing.Any] = None

    __G: str = "G"

    def to2(self, writer: typing.Union[io.TextIOWrapper, io.BufferedWriter]) -> None:
        self.__writer = Assertions.checkNotNull(
            writer, "Impossibe to export the graph in a null stream"
        )

        try:
            self._startSerialization()
            self._comment(
                format(
                    "Graph generated by Apache Commons Graph on %s%n",
                    datetime.datetime.now(),
                )
            )

            self._startGraph(self.__name)

            for vertex in self.__graph.getVertices0():
                properties = {}

                for vertexProperty in self.__vertexProperties.items():
                    properties[vertexProperty[0]] = vertexProperty[1].map(vertex)

                self._vertex(vertex, properties)

            for edge in self.__graph.getEdges():
                vertices = self.__graph.getVertices1(edge)

                properties = {}

                for edgeProperty in self.__edgeProperties.items():
                    properties[edgeProperty[0]] = edgeProperty[1].map(edge)

                self._edge(edge, vertices.getHead(), vertices.getTail(), properties)

            self._endGraph()

            self._endSerialization()
        except BaseException as e:
            raise GraphExportException(
                e,
                "an error occurred while exporting graph %s (named %s) to writer %s",
                self.__graph,
                self.__name,
                self.__writer,
            )
        finally:
            try:
                self.__writer.close()
            except IOError:
                pass

    def to1(
        self, outputStream: typing.Union[io.BytesIO, io.StringIO, io.BufferedWriter]
    ) -> None:
        self.to2(
            Assertions.checkNotNull(
                OutputStreamWriter(
                    outputStream, "Impossibe to export the graph in a null stream"
                )
            )
        )

    def to0(self, outputFile: pathlib.Path) -> None:
        try:
            self.to1(
                BytesIO(
                    Assertions.checkNotNull(
                        outputFile, "Impossibe to export the graph in a null file"
                    )
                )
            )
        except FileNotFoundError as e:
            raise RuntimeError(e)

    def _getWriter(self) -> typing.Union[io.TextIOWrapper, io.BufferedWriter]:
        return self.__writer

    def _getGraph(self) -> Graph[typing.Any, typing.Any]:
        return self.__graph

    def _addVertexProperty(
        self, propertyName: str, vertexProperty: typing.Dict[typing.Any, typing.Any]
    ) -> None:
        self.__vertexProperties.put(propertyName, vertexProperty)

    def _addEdgeProperty(
        self, propertyName: str, edgeProperty: typing.Dict[typing.Any, typing.Any]
    ) -> None:
        self.__edgeProperties.put(propertyName, edgeProperty)

    def __init__(self, graph: Graph[typing.Any, typing.Any], name: str) -> None:
        self.__graph = graph
        self.__writer = None
        self.__vertexProperties = {}
        self.__edgeProperties = {}
        self.__name = name if name is not None else self.__G

    def _vertex(
        self, vertex: typing.Any, properties: typing.Dict[str, typing.Any]
    ) -> None:
        pass

    def _startSerialization(self) -> None:
        pass

    def _startGraph(self, name: str) -> None:
        pass

    def _enlistVerticesProperty(self, name: str, type: typing.Type[typing.Any]) -> None:
        pass

    def _enlistEdgesProperty(self, name: str, type: typing.Type[typing.Any]) -> None:
        self._enlistProperty(name, type, self._edgeProperties)

    def _endSerialization(self) -> None:
        pass

    def _endGraph(self) -> None:
        pass

    def _edge(
        self,
        edge: typing.Any,
        head: typing.Any,
        tail: typing.Any,
        properties: typing.Dict[str, typing.Any],
    ) -> None:
        pass

    def _comment(self, text: str) -> None:
        pass
