/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:15:41 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.ChannelManagement;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ChannelManagement_ESTest extends ChannelManagement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[8];
      ChannelManagement channelManagement0 = null;
      try {
        channelManagement0 = new ChannelManagement(nMEAMessageArray0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.AISMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[1];
      ChannelManagement channelManagement0 = null;
      try {
        channelManagement0 = new ChannelManagement(nMEAMessageArray0, "010110");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Message of type ChannelManagement should be at exactly 168 bits long; not 6.
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.ChannelManagement", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[10];
      ChannelManagement channelManagement0 = null;
      try {
        channelManagement0 = new ChannelManagement(nMEAMessageArray0, "01011");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }
}
