/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:14:36 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.tbsalling.aismessages.ais.messages.Metadata;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Metadata_ESTest extends Metadata_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Instant instant0 = MockInstant.now();
      Metadata metadata0 = new Metadata("`&", instant0);
      metadata0.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Instant instant0 = MockInstant.now();
      Metadata metadata0 = new Metadata((String) null, instant0);
      String string0 = metadata0.getSource();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Instant instant0 = MockInstant.now();
      Metadata metadata0 = new Metadata("`&", instant0);
      String string0 = metadata0.getSource();
      assertEquals("`&", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      Clock clock0 = Clock.tickMillis(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata((String) null, instant0);
      metadata0.hashCode();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Instant instant0 = MockInstant.now();
      Metadata metadata0 = new Metadata((String) null, instant0);
      Metadata metadata1 = new Metadata("XM$(mO ", instant0);
      boolean boolean0 = metadata0.equals(metadata1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata("Sailing", instant0);
      Metadata metadata1 = new Metadata("{P|@;uw\"9[h5#[WIhI;", instant0);
      boolean boolean0 = metadata0.equals(metadata1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Instant instant0 = MockInstant.now();
      Metadata metadata0 = new Metadata((String) null, instant0);
      Metadata metadata1 = new Metadata((String) null, instant0);
      boolean boolean0 = metadata0.equals(metadata1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata("", instant0);
      Object object0 = new Object();
      boolean boolean0 = metadata0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      Clock clock0 = Clock.tickMillis(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata((String) null, instant0);
      boolean boolean0 = metadata0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Instant instant0 = MockInstant.now();
      Metadata metadata0 = new Metadata(" bO6*ati0!-y", instant0);
      boolean boolean0 = metadata0.equals(metadata0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata("", instant0);
      Metadata metadata1 = new Metadata("", instant0);
      boolean boolean0 = metadata0.equals(metadata1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata("", instant0);
      String string0 = metadata0.toString();
      assertEquals("Metadata{source='', received=2014-02-14T20:21:21Z}", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata("", instant0);
      String string0 = metadata0.getSource();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata("", instant0);
      Instant instant1 = metadata0.getReceived();
      assertSame(instant1, instant0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes((-1), (-1));
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      Instant instant0 = MockInstant.now(clock0);
      Metadata metadata0 = new Metadata("", instant0);
      String string0 = metadata0.getCategory();
      assertEquals("AIS", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Metadata metadata0 = new Metadata("", (Instant) null);
      String string0 = metadata0.getDecoderVersion();
      assertEquals("2.2.2", string0);
  }
}
