/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:09:13 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.PositionReportClassAScheduled;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PositionReportClassAScheduled_ESTest extends PositionReportClassAScheduled_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[2];
      PositionReportClassAScheduled positionReportClassAScheduled0 = null;
      try {
        positionReportClassAScheduled0 = new PositionReportClassAScheduled(nMEAMessageArray0, "010110");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.AISMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[0];
      PositionReportClassAScheduled positionReportClassAScheduled0 = null;
      try {
        positionReportClassAScheduled0 = new PositionReportClassAScheduled(nMEAMessageArray0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.AISMessage", e);
      }
  }
}
