/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:58:35 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.SafetyRelatedAcknowledge;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SafetyRelatedAcknowledge_ESTest extends SafetyRelatedAcknowledge_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[1];
      SafetyRelatedAcknowledge safetyRelatedAcknowledge0 = null;
      try {
        safetyRelatedAcknowledge0 = new SafetyRelatedAcknowledge(nMEAMessageArray0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.AISMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAMessage[] nMEAMessageArray0 = new NMEAMessage[15];
      SafetyRelatedAcknowledge safetyRelatedAcknowledge0 = null;
      try {
        safetyRelatedAcknowledge0 = new SafetyRelatedAcknowledge(nMEAMessageArray0, "001101");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Message of type SafetyRelatedAcknowledge should be exactly 72, 104, 136 or 168 bits long; not 6.
         //
         verifyException("dk.tbsalling.aismessages.ais.messages.SafetyRelatedAcknowledge", e);
      }
  }
}
