/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:03:33 GMT 2024
 */

package dk.tbsalling.aismessages.nmea.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.tbsalling.aismessages.nmea.exceptions.NMEAParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NMEAParseException_ESTest extends NMEAParseException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAParseException nMEAParseException0 = new NMEAParseException((String) null, "#)+`c/iYQ'q\"1w5");
      String string0 = nMEAParseException0.getMessage();
      assertEquals("#)+`c/iYQ'q\"1w5: null", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAParseException nMEAParseException0 = new NMEAParseException("#)+`c/iYQ'q\"1w5", (String) null);
      String string0 = nMEAParseException0.getRawMessage();
      assertEquals("#)+`c/iYQ'q\"1w5", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NMEAParseException nMEAParseException0 = new NMEAParseException("", "r\"1_:");
      String string0 = nMEAParseException0.getRawMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NMEAParseException nMEAParseException0 = new NMEAParseException("#)+`c/iYQ'q\"1w5", (String) null);
      String string0 = nMEAParseException0.getErrorDescription();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NMEAParseException nMEAParseException0 = new NMEAParseException("", "");
      String string0 = nMEAParseException0.getErrorDescription();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NMEAParseException nMEAParseException0 = new NMEAParseException((String) null, "#)+`c/iYQ'q\"1w5");
      String string0 = nMEAParseException0.getErrorDescription();
      assertEquals("#)+`c/iYQ'q\"1w5", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      NMEAParseException nMEAParseException0 = new NMEAParseException((String) null, "#)+`c/iYQ'q\"1w5");
      String string0 = nMEAParseException0.getRawMessage();
      assertNull(string0);
  }
}
