/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:02:27 GMT 2024
 */

package dk.tbsalling.aismessages.nmea.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.tbsalling.aismessages.nmea.exceptions.UnsupportedMessageType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UnsupportedMessageType_ESTest extends UnsupportedMessageType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnsupportedMessageType unsupportedMessageType0 = new UnsupportedMessageType("");
  }
}
