from __future__ import annotations
from abc import ABC
import pathlib
from io import StringIO
import io
from io import BytesIO
import typing
from typing import *
from src.main.org.apache.commons.graph.Graph import *
from src.main.org.apache.commons.graph.Mapper import *
from src.main.org.apache.commons.graph.VertexPair import *
from src.main.org.apache.commons.graph.export.GraphExportException import *
from src.main.org.apache.commons.graph.utils.Assertions import *


class AbstractExporter(ABC):

    __writer: typing.Union[io.TextIOWrapper, io.BufferedWriter] = None
    __name: str = None
    __edgeProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None
    __vertexProperties: typing.Dict[str, Mapper[typing.Any, typing.Any]] = None
    __graph: Graph[typing.Any, typing.Any] = None

    __G: str = "G"

    def to2(self, writer: typing.Union[io.TextIOWrapper, io.BufferedWriter]) -> None:

        self.__writer = checkNotNull(
            writer, "Impossibe to export the graph in a null stream"
        )

        try:
            self._startSerialization()
            self._comment(
                f"Graph generated by Apache Commons Graph on {datetime.now()}%n"
            )

            self._startGraph(self.__name)

            for vertex in self.__graph.getVertices0():
                properties = {
                    vertexProperty.getKey(): vertexProperty.getValue().map(vertex)
                    for vertexProperty in self.__vertexProperties.items()
                }

                self._vertex(vertex, properties)

            for edge in self.__graph.getEdges():
                vertices = self.__graph.getVertices1(edge)

                properties = {
                    edgeProperty.getKey(): edgeProperty.getValue().map(edge)
                    for edgeProperty in self.__edgeProperties.items()
                }

                self._edge(edge, vertices.getHead(), vertices.getTail(), properties)

            self._endGraph()

            self._endSerialization()
        except Exception as e:
            raise GraphExportException(
                e,
                f"an error occurred while exporting graph {self.__graph} (named {self.__name}) to writer {self.__writer}",
            )
        finally:
            try:
                self.__writer.close()
            except IOError:
                pass

    def to1(
        self, outputStream: typing.Union[io.BytesIO, io.StringIO, io.BufferedWriter]
    ) -> None:

        from src.main.org.apache.commons.graph.utils.Assertions import checkNotNull

        self.to2(
            io.TextIOWrapper(
                checkNotNull(
                    outputStream, "Impossibe to export the graph in a null stream"
                )
            )
        )

    def to0(self, outputFile: pathlib.Path) -> None:

        try:
            self.to1(
                open(
                    Assertions.checkNotNull(
                        outputFile, "Impossibe to export the graph in a null file"
                    ),
                    "wb",
                )
            )
        except FileNotFoundError as e:
            raise RuntimeError(e)

    def _getWriter(self) -> typing.Union[io.TextIOWrapper, io.BufferedWriter]:

        return self.__writer

    def _getGraph(self) -> Graph[typing.Any, typing.Any]:

        return self.__graph

    def _addVertexProperty(
        self, propertyName: str, vertexProperty: typing.Dict[typing.Any, typing.Any]
    ) -> None:

        if self.__vertexProperties is None:
            self.__vertexProperties = {}

        self.__vertexProperties[propertyName] = vertexProperty

    def _addEdgeProperty(
        self, propertyName: str, edgeProperty: typing.Dict[typing.Any, typing.Any]
    ) -> None:

        if self.__edgeProperties is None:
            self.__edgeProperties = {}

        self.__edgeProperties[propertyName] = edgeProperty

    def __init__(self, graph: Graph[typing.Any, typing.Any], name: str) -> None:

        self.__graph = graph
        self.__writer = None
        self.__vertexProperties = {}
        self.__edgeProperties = {}
        self.__name = name if name is not None else self.__G

    def _vertex(
        self, vertex: typing.Any, properties: typing.Dict[str, typing.Any]
    ) -> None:

        pass

    def _startSerialization(self) -> None:

        # The Java code does not throw any exceptions, so there is no need to translate it into Python.
        # If you want to raise an exception in Python, you can use the 'raise' keyword.
        # For example:
        # raise Exception("This method is not implemented")

        pass

    def _startGraph(self, name: str) -> None:

        self.__name = name
        self.__G = Graph()

    def _enlistVerticesProperty(self, name: str, type: typing.Type[typing.Any]) -> None:

        pass

    def _enlistEdgesProperty(self, name: str, type: typing.Type[typing.Any]) -> None:

        pass

    def _endSerialization(self) -> None:

        # The Java method is declared as "throws Exception", so we need to handle it in Python.
        # However, in this case, the method does not throw any exception, so we can leave it empty.
        pass

    def _endGraph(self) -> None:

        raise NotImplementedError("Subclass must implement abstract method")

    def _edge(
        self,
        edge: typing.Any,
        head: typing.Any,
        tail: typing.Any,
        properties: typing.Dict[str, typing.Any],
    ) -> None:

        pass

    def _comment(self, text: str) -> None:

        pass
