/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:55:40 GMT 2024
 */

package me.lemire.longcompression.differential;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.longcompression.differential.LongDelta;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LongDelta_ESTest extends LongDelta_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      long[] longArray0 = new long[5];
      // Undeclared exception!
      try { 
        LongDelta.fastinverseDelta(longArray0, 0, (-1594), 96);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      long[] longArray0 = new long[9];
      // Undeclared exception!
      try { 
        LongDelta.fastinverseDelta(longArray0, 1, 2244, (-782));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 9 out of bounds for length 9
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      long[] longArray0 = new long[8];
      longArray0[0] = (-960L);
      LongDelta.fastinverseDelta(longArray0);
      assertArrayEquals(new long[] {(-960L), (-960L), (-960L), (-960L), (-960L), (-960L), (-960L), (-960L)}, longArray0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      long[] longArray0 = new long[9];
      longArray0[2] = 124L;
      LongDelta.inverseDelta(longArray0);
      assertArrayEquals(new long[] {0L, 0L, 124L, 124L, 124L, 124L, 124L, 124L, 124L}, longArray0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      long[] longArray0 = new long[0];
      LongDelta.inverseDelta(longArray0);
      assertArrayEquals(new long[] {}, longArray0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      long[] longArray0 = new long[2];
      longArray0[0] = 3124L;
      // Undeclared exception!
      try { 
        LongDelta.delta(longArray0, (-1), 3, 11, longArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      long[] longArray0 = new long[9];
      long[] longArray1 = new long[4];
      LongDelta.delta(longArray0, 3, 3, 35, longArray1);
      assertArrayEquals(new long[] {(-35L), 0L, 0L, 0L}, longArray1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      long[] longArray0 = new long[9];
      LongDelta.delta(longArray0, 3, (-1), 0, longArray0);
      assertArrayEquals(new long[] {0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L}, longArray0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      long[] longArray0 = new long[2];
      LongDelta.delta(longArray0, 1, 0, 2);
      assertArrayEquals(new long[] {0L, (-2L)}, longArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      long[] longArray0 = new long[0];
      LongDelta.delta(longArray0);
      assertArrayEquals(new long[] {}, longArray0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      long[] longArray0 = new long[9];
      long long0 = LongDelta.fastinverseDelta(longArray0, 0, 1, 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      long[] longArray0 = new long[9];
      longArray0[1] = 2308L;
      long long0 = LongDelta.delta(longArray0, 1, 1, 23, longArray0);
      assertArrayEquals(new long[] {2285L, 2308L, 0L, 0L, 0L, 0L, 0L, 0L, 0L}, longArray0);
      assertEquals(2308L, long0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      long[] longArray0 = new long[9];
      longArray0[5] = (-985L);
      long long0 = LongDelta.delta(longArray0, 3, 3, 3, longArray0);
      assertArrayEquals(new long[] {(-3L), 0L, (-985L), 0L, 0L, (-985L), 0L, 0L, 0L}, longArray0);
      assertEquals((-985L), long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      long[] longArray0 = new long[2];
      longArray0[1] = (long) 1;
      long long0 = LongDelta.delta(longArray0, 1, 1, 0);
      assertEquals(1L, long0);
      assertArrayEquals(new long[] {0L, 1L}, longArray0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      long[] longArray0 = new long[7];
      longArray0[1] = (-1L);
      LongDelta.fastinverseDelta(longArray0);
      long long0 = LongDelta.delta(longArray0, 0, 3, (-1));
      assertArrayEquals(new long[] {1L, (-1L), 0L, (-1L), (-1L), (-1L), (-1L)}, longArray0);
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        LongDelta.inverseDelta((long[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        LongDelta.fastinverseDelta((long[]) null, 2720, 2720, 2720);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        LongDelta.fastinverseDelta((long[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        LongDelta.delta((long[]) null, 2720, 2720, 2720, (long[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try { 
        LongDelta.delta((long[]) null, 2720, 2720, 2720);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      long[] longArray0 = new long[16];
      // Undeclared exception!
      try { 
        LongDelta.delta(longArray0, 3, (-1504), 2251);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1502 out of bounds for length 16
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try { 
        LongDelta.delta((long[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      long[] longArray0 = new long[20];
      long long0 = LongDelta.fastinverseDelta(longArray0, 8, 8, 8);
      assertEquals(8L, long0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      long[] longArray0 = new long[16];
      LongDelta.fastinverseDelta(longArray0, 6, 6, 2164);
      LongDelta.delta(longArray0);
      assertEquals(16, longArray0.length);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      long[] longArray0 = new long[8];
      long long0 = LongDelta.fastinverseDelta(longArray0, 3, 3, (-168));
      assertArrayEquals(new long[] {0L, 0L, 0L, (-168L), (-168L), (-168L), 0L, 0L}, longArray0);
      assertEquals((-168L), long0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      long[] longArray0 = new long[0];
      // Undeclared exception!
      try { 
        LongDelta.fastinverseDelta(longArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 0
         //
         verifyException("me.lemire.longcompression.differential.LongDelta", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LongDelta longDelta0 = new LongDelta();
  }
}
