/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:54:30 GMT 2024
 */

package me.lemire.longcompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.integercompression.OptPFDS9;
import me.lemire.longcompression.LongAs2IntsCodec;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LongAs2IntsCodec_ESTest extends LongAs2IntsCodec_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      long[] longArray0 = new long[8];
      IntWrapper intWrapper0 = new IntWrapper(2);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      longAs2IntsCodec0.compress(longArray0, intWrapper1, 1, longArray0, intWrapper1);
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.uncompress(longArray0, intWrapper0, 48, longArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      long[] longArray0 = new long[9];
      IntWrapper intWrapper0 = new IntWrapper(4);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      intWrapper1.increment();
      longAs2IntsCodec0.compress(longArray0, intWrapper1, 4, longArray0, intWrapper0);
      long[] longArray1 = new long[9];
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.uncompress(longArray0, intWrapper1, 4, longArray1, intWrapper1);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      long[] longArray0 = new long[9];
      IntWrapper intWrapper0 = new IntWrapper(4);
      long[] longArray1 = new long[9];
      longAs2IntsCodec0.uncompress(longArray0, intWrapper0, 4, longArray1, intWrapper0);
      assertArrayEquals(new long[] {0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L}, longArray1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      long[] longArray0 = new long[9];
      IntWrapper intWrapper0 = new IntWrapper(4);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      longAs2IntsCodec0.uncompress(longArray0, intWrapper1, 4, longArray0, intWrapper0);
      assertEquals("4", intWrapper1.toString());
      assertEquals(4.0, intWrapper1.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      IntWrapper intWrapper0 = new IntWrapper(4);
      long[] longArray0 = new long[8];
      longArray0[5] = (-590L);
      longArray0[7] = (-1778L);
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.compress(longArray0, intWrapper0, 4, longArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OptPFDS9 optPFDS9_0 = new OptPFDS9();
      LongAs2IntsCodec longAs2IntsCodec0 = new LongAs2IntsCodec(optPFDS9_0, optPFDS9_0);
      long[] longArray0 = new long[9];
      IntWrapper intWrapper0 = new IntWrapper(0);
      long[] longArray1 = new long[8];
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.compress(longArray1, intWrapper0, 331, longArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      IntWrapper intWrapper0 = new IntWrapper((-819));
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.uncompress((long[]) null, intWrapper0, (-819), (long[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      long[] longArray0 = new long[6];
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.uncompress(longArray0, intWrapper0, (-1290), longArray0, intWrapper0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -20640
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      long[] longArray0 = new long[1];
      longArray0[0] = (long) 6983;
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.uncompress(longArray0, intWrapper0, 6983, longArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      IntWrapper intWrapper0 = new IntWrapper(256);
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.compress((long[]) null, intWrapper0, 256, (long[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      long[] longArray0 = new long[6];
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      IntWrapper intWrapper0 = new IntWrapper((-1022));
      // Undeclared exception!
      try { 
        longAs2IntsCodec0.compress(longArray0, intWrapper0, (-1022), longArray0, intWrapper0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -1022
         //
         verifyException("me.lemire.longcompression.LongAs2IntsCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      long[] longArray0 = new long[10];
      IntWrapper intWrapper0 = new IntWrapper(4);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      longAs2IntsCodec0.compress(longArray0, intWrapper1, 4, longArray0, intWrapper0);
      longAs2IntsCodec0.uncompress(longArray0, intWrapper1, 4, longArray0, intWrapper1);
      assertEquals(8.0, intWrapper1.doubleValue(), 0.01);
      assertEquals(8, intWrapper1.intValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      long[] longArray0 = new long[8];
      IntWrapper intWrapper0 = new IntWrapper(0);
      longAs2IntsCodec0.uncompress(longArray0, intWrapper0, 0, longArray0, intWrapper0);
      assertEquals((short)0, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OptPFDS9 optPFDS9_0 = new OptPFDS9();
      LongAs2IntsCodec longAs2IntsCodec0 = new LongAs2IntsCodec(optPFDS9_0, optPFDS9_0);
      long[] longArray0 = new long[9];
      IntWrapper intWrapper0 = new IntWrapper(1);
      longAs2IntsCodec0.compress(longArray0, intWrapper0, 1, longArray0, intWrapper0);
      assertEquals((byte)2, intWrapper0.byteValue());
      assertArrayEquals(new long[] {0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L}, longArray0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LongAs2IntsCodec longAs2IntsCodec0 = LongAs2IntsCodec.LongAs2IntsCodec1();
      long[] longArray0 = new long[22];
      IntWrapper intWrapper0 = new IntWrapper(0);
      longAs2IntsCodec0.compress(longArray0, intWrapper0, 0, longArray0, intWrapper0);
      assertEquals((byte)0, intWrapper0.byteValue());
      assertEquals(0, intWrapper0.intValue());
  }
}
