/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:52:14 GMT 2024
 */

package me.lemire.longcompression;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Comparator;
import me.lemire.longcompression.RoaringIntPacking;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RoaringIntPacking_ESTest extends RoaringIntPacking_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = RoaringIntPacking.toUnsignedString(0);
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      long long0 = RoaringIntPacking.pack(0, 0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      long long0 = RoaringIntPacking.pack((-81), (-81));
      assertEquals((-343597383761L), long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = RoaringIntPacking.low(Integer.MAX_VALUE);
      assertEquals(Integer.MAX_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = RoaringIntPacking.low((-1L));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = RoaringIntPacking.high(642L);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = RoaringIntPacking.high((-22L));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = RoaringIntPacking.compareUnsigned((-1), (-2961));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = RoaringIntPacking.compareUnsigned(0, 1383);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = RoaringIntPacking.toUnsignedString((-1));
      assertEquals("18446744073709551615", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = RoaringIntPacking.toUnsignedString(Integer.MAX_VALUE);
      assertEquals("2147483647", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int int0 = RoaringIntPacking.highestHigh(true);
      assertEquals(Integer.MAX_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int int0 = RoaringIntPacking.highestHigh(false);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int int0 = RoaringIntPacking.high(14873471746048L);
      assertEquals(3463, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      long long0 = RoaringIntPacking.pack(3463, 0);
      assertEquals(14873471746048L, long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int int0 = RoaringIntPacking.low(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Comparator<Integer> comparator0 = RoaringIntPacking.unsignedComparator();
      assertNotNull(comparator0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int int0 = RoaringIntPacking.compareUnsigned(Integer.MAX_VALUE, Integer.MAX_VALUE);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      RoaringIntPacking roaringIntPacking0 = new RoaringIntPacking();
  }
}
