/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:49:20 GMT 2024
 */

package me.lemire.longcompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.IntWrapper;
import me.lemire.longcompression.LongJustCopy;
import me.lemire.longcompression.LongVariableByte;
import me.lemire.longcompression.SkippableLongCODEC;
import me.lemire.longcompression.SkippableLongComposition;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SkippableLongComposition_ESTest extends SkippableLongComposition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LongVariableByte longVariableByte0 = new LongVariableByte();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longVariableByte0, longVariableByte0);
      LongJustCopy longJustCopy0 = new LongJustCopy();
      skippableLongComposition0.F1 = (SkippableLongCODEC) longJustCopy0;
      String string0 = skippableLongComposition0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LongVariableByte longVariableByte0 = new LongVariableByte();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longVariableByte0, longVariableByte0);
      IntWrapper intWrapper0 = new IntWrapper(1);
      long[] longArray0 = new long[7];
      skippableLongComposition0.headlessUncompress((long[]) null, intWrapper0, 1, longArray0, intWrapper0, (-1976));
      assertEquals((short)2, intWrapper0.shortValue());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LongVariableByte longVariableByte0 = new LongVariableByte();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longVariableByte0, longVariableByte0);
      long[] longArray0 = new long[4];
      IntWrapper intWrapper0 = new IntWrapper((-1));
      SkippableLongComposition skippableLongComposition1 = new SkippableLongComposition(longVariableByte0, skippableLongComposition0);
      skippableLongComposition1.headlessUncompress(longArray0, intWrapper0, 0, longArray0, intWrapper0, 0);
      assertEquals((byte)1, intWrapper0.byteValue());
      assertEquals(1, intWrapper0.intValue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LongJustCopy longJustCopy0 = new LongJustCopy();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longJustCopy0, longJustCopy0);
      long[] longArray0 = new long[1];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      skippableLongComposition0.headlessUncompress(longArray0, intWrapper0, 2367, longArray0, intWrapper1, 0);
      assertEquals((short)1, intWrapper0.shortValue());
      assertEquals(1.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LongVariableByte longVariableByte0 = new LongVariableByte();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longVariableByte0, longVariableByte0);
      long[] longArray0 = new long[4];
      IntWrapper intWrapper0 = new IntWrapper(1);
      long[] longArray1 = new long[4];
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessCompress(longArray0, intWrapper0, 0, longArray1, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity < 0: (-16 < 0)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LongVariableByte longVariableByte0 = new LongVariableByte();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longVariableByte0, longVariableByte0);
      LongJustCopy longJustCopy0 = new LongJustCopy();
      skippableLongComposition0.F2 = (SkippableLongCODEC) longJustCopy0;
      long[] longArray0 = new long[4];
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessCompress(longArray0, intWrapper0, 0, longArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LongVariableByte longVariableByte0 = new LongVariableByte();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longVariableByte0, longVariableByte0);
      long[] longArray0 = new long[4];
      IntWrapper intWrapper0 = new IntWrapper(1);
      IntWrapper intWrapper1 = IntWrapper.IntWrapper1();
      skippableLongComposition0.headlessCompress(longArray0, intWrapper0, 0, longArray0, intWrapper1);
      assertEquals((byte)1, intWrapper1.byteValue());
      assertEquals(1.0, intWrapper0.doubleValue(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition((SkippableLongCODEC) null, (SkippableLongCODEC) null);
      // Undeclared exception!
      try { 
        skippableLongComposition0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LongJustCopy longJustCopy0 = new LongJustCopy();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longJustCopy0, longJustCopy0);
      IntWrapper intWrapper0 = new IntWrapper((-1));
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessUncompress((long[]) null, intWrapper0, (-1), (long[]) null, intWrapper0, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LongJustCopy longJustCopy0 = new LongJustCopy();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longJustCopy0, longJustCopy0);
      IntWrapper intWrapper0 = new IntWrapper(204);
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessCompress((long[]) null, intWrapper0, 204, (long[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LongVariableByte longVariableByte0 = new LongVariableByte();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longVariableByte0, longVariableByte0);
      long[] longArray0 = new long[4];
      IntWrapper intWrapper0 = new IntWrapper(0);
      long[] longArray1 = new long[0];
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessCompress(longArray0, intWrapper0, 1, longArray1, intWrapper0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LongJustCopy longJustCopy0 = new LongJustCopy();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longJustCopy0, longJustCopy0);
      long[] longArray0 = new long[8];
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessUncompress(longArray0, intWrapper0, 0, longArray0, intWrapper0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LongJustCopy longJustCopy0 = new LongJustCopy();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longJustCopy0, longJustCopy0);
      long[] longArray0 = new long[3];
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessUncompress(longArray0, intWrapper0, 1, longArray0, intWrapper0, 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LongJustCopy longJustCopy0 = new LongJustCopy();
      SkippableLongComposition skippableLongComposition0 = new SkippableLongComposition(longJustCopy0, longJustCopy0);
      long[] longArray0 = new long[18];
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        skippableLongComposition0.headlessCompress(longArray0, intWrapper0, 1, longArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }
}
