/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:27:22 GMT 2024
 */

package me.lemire.integercompression.synth;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.synth.ClusteredDataGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ClusteredDataGenerator_ESTest extends ClusteredDataGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Random.setNextRandom((-95));
      // Undeclared exception!
      ClusteredDataGenerator.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = clusteredDataGenerator0.generateClustered(1457, 1457);
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillClustered(intArray0, 37, 1457, 2104, (-519));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -4080
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = new int[4];
      clusteredDataGenerator0.fillUniform(intArray0, (-536), 0, (-459), 2048);
      assertEquals(4, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = new int[9];
      clusteredDataGenerator0.fillClustered(intArray0, 0, 0, 0, 0);
      assertEquals(9, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      Random.setNextRandom(36);
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.generateClustered(36, 7);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -29
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = clusteredDataGenerator0.generateClustered(0, 0);
      assertArrayEquals(new int[] {}, intArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      // Undeclared exception!
      clusteredDataGenerator0.generateClustered(877, 1323);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      clusteredDataGenerator0.unidg = null;
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.generateClustered(409, 409);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.synth.ClusteredDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      clusteredDataGenerator0.fillUniform(intArray0, 223, 223, (-2006), (-1));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillUniform((int[]) null, (-1), (-1), 3375, (-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // not possible
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillUniform((int[]) null, 233, 1, 1, 233);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.synth.ClusteredDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillUniform(intArray0, 3998, 3998, 3998, 3998);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -3998
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = clusteredDataGenerator0.generateClustered(1115, 1115);
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillUniform(intArray0, 1115, 1115, 0, 1115);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1115 out of bounds for length 1115
         //
         verifyException("me.lemire.integercompression.synth.ClusteredDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillClustered((int[]) null, (-2), (-2), 2, (-2));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // not possible
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillClustered((int[]) null, 1000, 1000, 1000, 1000);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.synth.ClusteredDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = clusteredDataGenerator0.generateClustered(38, 38);
      // Undeclared exception!
      try { 
        clusteredDataGenerator0.fillClustered(intArray0, 38, 38, 38, 38);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 38 out of bounds for length 38
         //
         verifyException("me.lemire.integercompression.synth.ClusteredDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      int[] intArray0 = clusteredDataGenerator0.generateClustered(848, 848);
      // Undeclared exception!
      clusteredDataGenerator0.fillClustered(intArray0, 20, 848, 20, 3547);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ClusteredDataGenerator clusteredDataGenerator0 = new ClusteredDataGenerator();
      clusteredDataGenerator0.generateClustered(44, 45);
      // Undeclared exception!
      ClusteredDataGenerator.main((String[]) null);
  }
}
