/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 13:26:10 GMT 2024
 */

package me.lemire.integercompression.synth;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.synth.UniformDataGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockRandom;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UniformDataGenerator_ESTest extends UniformDataGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-505), 401);
      MockRandom mockRandom0 = new MockRandom();
      mockRandom0.nextLong();
      int[] intArray0 = uniformDataGenerator0.generateUniformBitmap(1, 401);
      assertArrayEquals(new int[] {1}, intArray0);
      assertEquals(1, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[1] = 26624;
      // Undeclared exception!
      UniformDataGenerator.negate(intArray0, 26624);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(1, (-684));
      int[] intArray0 = uniformDataGenerator0.generateUniformHash(1, 338);
      assertEquals(1, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(2048, 2048);
      int[] intArray0 = uniformDataGenerator0.generateUniformBitmap(0, 0);
      assertArrayEquals(new int[] {}, intArray0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(0, (-1084));
      int[] intArray0 = uniformDataGenerator0.generateUniform(0, 0);
      int[] intArray1 = UniformDataGenerator.negate(intArray0, 0);
      assertNotSame(intArray1, intArray0);
      assertEquals(0, intArray1.length);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        UniformDataGenerator.negate((int[]) null, 973);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        UniformDataGenerator.negate(intArray0, (-83));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -83
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 1453;
      // Undeclared exception!
      try { 
        UniformDataGenerator.negate(intArray0, 1453);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(116, 116);
      // Undeclared exception!
      uniformDataGenerator0.generateUniformHash(116, 116);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(167, 167);
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniformHash(167, 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // not possible
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(1032, 1032);
      uniformDataGenerator0.rand = null;
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniformHash(1032, 1032);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-2622), (-2622));
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniformHash((-2622), (-2622));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -2622
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(167, 167);
      // Undeclared exception!
      uniformDataGenerator0.generateUniformBitmap(167, 167);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(4, 4);
      uniformDataGenerator0.rand = null;
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniformBitmap(4, 4);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-13), (-13));
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniformBitmap((-13), (-13));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -13
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-1554), 0);
      uniformDataGenerator0.rand = null;
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniform(339, 341);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-2181), (-2181));
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniform((-2181), (-2181));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -2181
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-505), 401);
      int[] intArray0 = uniformDataGenerator0.generateUniformBitmap(1, 401);
      assertArrayEquals(new int[] {0}, intArray0);
      assertEquals(1, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-505), 401);
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniformBitmap(1, (-2450));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // not possible
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(2, 2);
      // Undeclared exception!
      uniformDataGenerator0.generateUniform(2, 419);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      int[] intArray0 = new int[7];
      intArray0[0] = 28;
      // Undeclared exception!
      UniformDataGenerator.negate(intArray0, 26624);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-10), (-10));
      // Undeclared exception!
      try { 
        uniformDataGenerator0.generateUniform((-10), (-2606));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // not possible
         //
         verifyException("me.lemire.integercompression.synth.UniformDataGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator(0, 0);
      int[] intArray0 = uniformDataGenerator0.generateUniformHash(0, 0);
      assertEquals(0, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      UniformDataGenerator uniformDataGenerator0 = new UniformDataGenerator((-505), 401);
      int[] intArray0 = uniformDataGenerator0.generateUniform(401, 401);
      int[] intArray1 = UniformDataGenerator.negate(intArray0, 1333);
      assertEquals(932, intArray1.length);
  }
}
