/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:06:55 GMT 2024
 */

package dk.tbsalling.aismessages.nmea.messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NMEAMessage_ESTest extends NMEAMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString("(%'<N73Q");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // (%'<N73Q
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString(",");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString("r=VDO");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Message does not comply with regexp \"^!.*\\*[0-9A-Fa-f]{2}$\": r=VDO
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString("z=VDM");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Message does not comply with regexp \"^!.*\\*[0-9A-Fa-f]{2}$\": z=VDM
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString(">3Q");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // >3Q
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString("(<>3Q");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // (<>3Q
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        NMEAMessage.fromString("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.nmea.messages.NMEAMessage", e);
      }
  }
}
