/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:23:13 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages.types;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.types.ITDMACommunicationState;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ITDMACommunicationState_ESTest extends ITDMACommunicationState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ITDMACommunicationState iTDMACommunicationState0 = ITDMACommunicationState.fromBitString("dk.tbsalling.aismessages.ais.messages.types.ITDMACommunicationState");
      assertNull(iTDMACommunicationState0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        ITDMACommunicationState.fromBitString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ITDMACommunicationState iTDMACommunicationState0 = ITDMACommunicationState.fromBitString("~9e-T14~T7Ws2}AESSH");
      assertNull(iTDMACommunicationState0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ITDMACommunicationState iTDMACommunicationState0 = ITDMACommunicationState.fromBitString("b1ve()");
      assertNull(iTDMACommunicationState0);
  }
}
