/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:28:32 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages.types;

import org.junit.Test;
import static org.junit.Assert.*;
import dk.tbsalling.aismessages.ais.messages.types.MMSI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MMSI_ESTest extends MMSI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MMSI mMSI0 = new MMSI(856);
      MMSI mMSI1 = MMSI.valueOf(6044);
      boolean boolean0 = mMSI0.equals(mMSI1);
      assertFalse(mMSI1.equals((Object)mMSI0));
      assertFalse(boolean0);
      assertEquals(6044, (int)mMSI1.getMMSI());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MMSI mMSI0 = new MMSI(0);
      Integer integer0 = mMSI0.getMMSI();
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MMSI mMSI0 = MMSI.valueOf(2951);
      Integer integer0 = mMSI0.getMMSI();
      assertEquals(2951, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MMSI mMSI0 = MMSI.valueOf((-217));
      MMSI mMSI1 = new MMSI((-217));
      boolean boolean0 = mMSI0.equals(mMSI1);
      assertEquals((-217), (int)mMSI1.getMMSI());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MMSI mMSI0 = new MMSI(856);
      boolean boolean0 = mMSI0.equals("MMSI [mmsi=6044]");
      assertEquals(856, (int)mMSI0.getMMSI());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MMSI mMSI0 = MMSI.valueOf((-651));
      boolean boolean0 = mMSI0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals((-651), (int)mMSI0.getMMSI());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MMSI mMSI0 = new MMSI(0);
      boolean boolean0 = mMSI0.equals(mMSI0);
      assertEquals(0, (int)mMSI0.getMMSI());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MMSI mMSI0 = new MMSI(856);
      MMSI mMSI1 = MMSI.valueOf(6044);
      boolean boolean0 = mMSI1.equals(mMSI0);
      assertFalse(boolean0);
      assertEquals(6044, (int)mMSI1.getMMSI());
      assertFalse(mMSI0.equals((Object)mMSI1));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MMSI mMSI0 = new MMSI(856);
      mMSI0.hashCode();
      assertEquals(856, (int)mMSI0.getMMSI());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MMSI mMSI0 = new MMSI(856);
      String string0 = mMSI0.toString();
      assertEquals("MMSI [mmsi=856]", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MMSI mMSI0 = MMSI.valueOf((-1340));
      Integer integer0 = mMSI0.getMMSI();
      assertEquals((-1340), (int)integer0);
  }
}
