/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:31:42 GMT 2024
 */

package dk.tbsalling.aismessages.ais.messages.types;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.types.SOTDMACommunicationState;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SOTDMACommunicationState_ESTest extends SOTDMACommunicationState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SOTDMACommunicationState sOTDMACommunicationState0 = SOTDMACommunicationState.fromBitString(": Out of range.");
      assertNull(sOTDMACommunicationState0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        SOTDMACommunicationState.fromBitString((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SOTDMACommunicationState sOTDMACommunicationState0 = SOTDMACommunicationState.fromBitString("dk.tbsalling.aismessages.ais.messages.types.SOTDMACommunicationState");
      assertNull(sOTDMACommunicationState0);
  }
}
