/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:05:48 GMT 2024
 */

package dk.tbsalling.aismessages.nmea;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.nmea.NMEAMessageSocketClient;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NMEAMessageSocketClient_ESTest extends NMEAMessageSocketClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NMEAMessageSocketClient nMEAMessageSocketClient0 = null;
      try {
        nMEAMessageSocketClient0 = new NMEAMessageSocketClient("", (Integer) null, (Consumer<? super NMEAMessage>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.nmea.NMEAMessageSocketClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-1));
      NMEAMessageSocketClient nMEAMessageSocketClient0 = null;
      try {
        nMEAMessageSocketClient0 = new NMEAMessageSocketClient("", integer0, (Consumer<? super NMEAMessage>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // port out of range:-1
         //
         verifyException("java.net.InetSocketAddress", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer integer0 = new Integer(2957);
      NMEAMessageSocketClient nMEAMessageSocketClient0 = new NMEAMessageSocketClient("", integer0, (Consumer<? super NMEAMessage>) null);
      nMEAMessageSocketClient0.requestStop();
  }
}
