/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:02:24 GMT 2024
 */

package dk.tbsalling.aismessages.nmea;

import java.io.InputStream;
import java.util.function.Consumer;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import static org.evosuite.shaded.org.mockito.Mockito.mock;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NMEAMessageInputStreamReader_ESTest extends NMEAMessageInputStreamReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      NMEAMessageInputStreamReader nMEAMessageInputStreamReader0 = new NMEAMessageInputStreamReader((InputStream) null, consumer0);
      assertFalse(nMEAMessageInputStreamReader0.isStopRequested());
      
      nMEAMessageInputStreamReader0.requestStop();
      Boolean boolean0 = nMEAMessageInputStreamReader0.isStopRequested();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      NMEAMessageInputStreamReader nMEAMessageInputStreamReader0 = new NMEAMessageInputStreamReader((InputStream) null, consumer0);
      Boolean boolean0 = nMEAMessageInputStreamReader0.isStopRequested();
      assertFalse(boolean0);
  }
}
