/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:04:43 GMT 2024
 */

package dk.tbsalling.aismessages.nmea;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dk.tbsalling.aismessages.ais.messages.AISMessage;
import dk.tbsalling.aismessages.nmea.NMEAMessageHandler;
import dk.tbsalling.aismessages.nmea.messages.NMEAMessage;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NMEAMessageHandler_ESTest extends NMEAMessageHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Consumer<Object>[] consumerArray0 = (Consumer<Object>[]) Array.newInstance(Consumer.class, 0);
      NMEAMessageHandler nMEAMessageHandler0 = new NMEAMessageHandler((String) null, consumerArray0);
      // Undeclared exception!
      try { 
        nMEAMessageHandler0.accept((NMEAMessage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.nmea.NMEAMessageHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NMEAMessageHandler nMEAMessageHandler0 = null;
      try {
        nMEAMessageHandler0 = new NMEAMessageHandler("6[?He @5?~of%h", (Consumer<? super AISMessage>[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dk.tbsalling.aismessages.nmea.NMEAMessageHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Consumer<Object>[] consumerArray0 = (Consumer<Object>[]) Array.newInstance(Consumer.class, 3);
      NMEAMessageHandler nMEAMessageHandler0 = new NMEAMessageHandler("MCVCl\"8", consumerArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Consumer<Object>[] consumerArray0 = (Consumer<Object>[]) Array.newInstance(Consumer.class, 0);
      NMEAMessageHandler nMEAMessageHandler0 = new NMEAMessageHandler("", consumerArray0);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      nMEAMessageHandler0.addAisMessageReceiver(consumer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Consumer<Object>[] consumerArray0 = (Consumer<Object>[]) Array.newInstance(Consumer.class, 0);
      NMEAMessageHandler nMEAMessageHandler0 = new NMEAMessageHandler("", consumerArray0);
      ArrayList<NMEAMessage> arrayList0 = nMEAMessageHandler0.flush();
      assertTrue(arrayList0.isEmpty());
  }
}
